### ISSUE TITLE
Long property names

### ISSUE THREAD

**Issue by Rogach** [scallop/scallop#10]
The possible input forms (propery name - "Props"):

```
--Props key1=value1
--Props key1=value1 key2=value2
--Props key1=value1 , key2=value2
--Props key1=value1, key2=value2
--Props key1=value1,key2=value2
```

Definition in ScallopConf:

```
val props = propsLong[String]("Props")
```

Value extraction as usual.

Commas in keys and values are disallowed, since they mark the next key-value pair.

**Comment by alexy** [comment]
I intuitively typed things like:

--Props a=1,b=2,c=3

--Propskey will be hard to read.  You can argue for

-Pa=1,b=2,c=3

better.
