### ISSUE TITLE
"Unknown option" exception, code executed though

### ISSUE THREAD

**Issue by camlostCZ** [scallop/scallop#101]
Hello,
this question has been asked bellow an article on the "Rogach on Scala" blog and moved here as requested.

What I want to achieve is an application with the following set of cmd line options:

```
app -m <email addr> ... load user account info
app -m <email addr> -c -f <firstname> -l <lastname> ... create a new account
app -m <email addr> -u --disable ... disable account
app -m <email addr> -u --enable ... enable account
```

and so on.
(I would prefer not using the -m: app example@domain.com but I cannot figure out how to do it so let's continue with the above.)

I've created a class to process the line args:

```
class Conf(arguments: Seq[String]) extends ScallopConf(arguments) {
    val mail = opt[String](required = true, descr = "User's e-mail address")
    val create = new Subcommand("-c") {
        val firstName = opt[String](required = true, short = 'f')
        val lastName = opt[String](required = true, short = 'l')
    }
    //val delete = opt[Boolean](descr = "Delete a user")
    val read = opt[Boolean](descr = "Read user information")
    val update = new Subcommand("-u") {
        val disable = opt[Boolean](descr = "Disable user account")
        val enable = opt[Boolean](descr = "Enable user account")
        mutuallyExclusive(disable, enable)
    }
    addSubcommand(create)
    addSubcommand(update)
    verify()
}
```

How can I check if a 'create' operation has been specified?
I've used this:

```
if (conf.create.firstName.isSupplied == true) {
...
}

```

but the code throws exception:
"Exception in thread "main" org.rogach.scallop.exceptions.UnknownOption: Unknown option 'f'
on this line:
`if (conf.update.enable()) {`

I call the code like this:
`app.run(Array("-m", "REDIM_NG-test3@csas.cz", "-c", "-f", "GivenName", "-l", "FamilyName"))`

Which calls this method:

```
    def run(args: Array[String]): Unit = {
        val conf = new Conf(args)
        val mgr = new AdminUserMgr(directorySvc)
        val mail = conf.mail()

        try {
            if (conf.create.firstName.isSupplied == true) {
                mgr.createUser(mail, conf.create.lastName(), conf.create.firstName())
                println(s"User account $mail has been created.")
            }
            if (conf.read()) {
                val user = mgr.getUser(mail)
                println(mgr.printUser(user))
            }
            if (conf.update.enable()) {
                mgr.enableUser(mail)
                println(s"User account $mail has been enabled.")
            }
            if (conf.update.disable()) {
                mgr.disableUser(mail)
                println(s"User account $mail has been disabled.")
            }
        } catch {
            case e: NoSuchElementException => println(e.getLocalizedMessage)
            case e: GoogleJsonResponseException => println(e.getLocalizedMessage)
        }
    }
```

The strange thing is that the specified account is created successfully (with correct first and last names) so the -f option has been processed correctly.

**Comment by Rogach** [comment]
ScallopConf provides `.subcommand()` method, which you can use to select the required code branch without calling undefined options:

``` scala
conf.subcommand match {
  case Some(conf.create) => 
    mgr.createUser(mail, conf.create.lastName(), conf.create.firstName())
    println(s"User account $mail has been created.")
  case Some(conf.read) =>
    val user = mgr.getUser(mail)
    println(mgr.printUser(user))
  case Some(conf.update) =>
    if (conf.update.enable()) {
      mgr.enableUser(mail)
      println(s"User account $mail has been enabled.")
    } else if (conf.update.disable()) {
      mgr.disableUser(mail)
      println(s"User account $mail has been disabled.")
    }
  case None => println("No subcommand was provided"
}
```

The way you used it you actually asked Scallop to parse command line with "create" options by using "update" configuration, which failed. I think that this is not what you intended anyway, and failing fast is the best option in such situations.

And that all happened after "create" options were already processed, thus explaining why account was created successfully.

About your request to get `app somebody@somewhere` form for your command line - since it is always provided and is always in the 0th position arguments, you can simply cut it out before passing arguments to scallop:

``` scala
def run(args: Array[String]) {
  val mail = args.head
  val conf = new Conf(args)
}
```

But that will complicate `--help` behavior - you'll need to check for that manually and correctly pass through in such cases.

**Comment by camlostCZ** [comment]
Thanks for such a detailed reply.

As 'read' is not a subcommand but an option, I've fixed the suggested code.

I have another question. As there isn't any forum, I'll ask here:
How to specify the options and the subcommands are mutually exclusive?
I can call mutuallyExclusive() for options only.

**Comment by Rogach** [comment]
I think you were referring to "-read" option vs other subcommands. One simple solution will be to make it subcommand as well (empty, without additional options).

Or you can check that `conf.subcommand` is `None` if `read.isSupplied`.
