### ISSUE TITLE
Converter

### ISSUE THREAD

**Issue by joriscode** [scallop/scallop#104]
Hi, I have a question which is certainly not an issue however, I don't know where else to ask.

When I compile the example of Custom Converter https://github.com/scallop/scallop/wiki/Custom-converters I get the following errors:

```
[error]  found   : org.rogach.scallop.ValueConverter[center.scala.sbk.Commands.Person]{val nameRgx: scala.util.matching.Regex; val phoneRgx: scala.util.matching.Regex}
[error]  required: String
[error] Error occurred in an application involving default arguments.
[error]     val person = opt[Person](personConverter)
[error]                                              ^
```

```
could not find implicit value for parameter conv: org.rogach.scallop.ValueConverter[center.scala.sbk.Commands.Person]
[error] Error occurred in an application involving default arguments.
[error]     val person = opt[Person](personConverter)
[error]                             ^
```

Thank you for your help. I would like very much to use your library over `scopt`.

**Comment by Rogach** [comment]
Hi!

That was a typo in the docs - you need an additional parens before `(personConverter)`, because converters are passed in implicit arguments.

The following should compile&work:

``` scala
val person = opt[Person]()(personConverter)
```

**Comment by joriscode** [comment]
Thank you for your quick answer!
I am going to continue now that I can convert to `case classes`.
Sorry for creating an issue, I did not find any other channel...

**Comment by Rogach** [comment]
You're welcome! Issues are exactly the right channel in this case, no problem.
