### ISSUE TITLE
ToggleOptions: flag for making it invocable only in 2 way, rather than 3 with no prefix?

### ISSUE THREAD

**Issue by mladibejn** [scallop/scallop#105]
Toggle option with name "verbose", it will be invocable in three ways -
    \* "--verbose", "--noverbose", "-v".

Did you consider having a flag that would make it invokable only with --verbose and -v, and not with prefix for untrue option? I found myself using the no + option by default in program that I wouldnt need to pass it as an option when executing.

**Comment by Rogach** [comment]
Don't exactly understand - if you don't need untrue option, why do you need toggle option? Can you use simple option instead?

**Comment by mladibejn** [comment]
I used toggle so I could invoke the command like "cmd -rma" with 3 options turned on. Having simple option I would need to pass an argument and could not stack them like this, right? What I want to achieve is that I print only --reset, since --noreset would be something by default, so I wouldnt confuse others in --help.

**Comment by Rogach** [comment]
You can use boolean option, which works as a flag:

``` scala
val verbose = opt[Boolean]()
```

This will allow you to stack it as well: `cmd -rmv` is equal to `cmd -rm --verbose`.

**Comment by mladibejn** [comment]
Cool, solved my problem, thanks a lot :)
