### ISSUE TITLE
Should an opt[Boolean] default be None?

### ISSUE THREAD

**Issue by alexy** [scallop/scallop#11]
I'm surprised by the Some(false) default, perhaps None is preferable?

**Comment by Rogach** [comment]
I can make it None, no problem, but again, what is the use case?

In the "standard" use case:

```
val apples = opt[Boolean]("apples")
apples() // either true or false
```

With `None` as default:

```
val apples = opt[Boolean]("apples")
apples() // will throw NoSuchElementException if flag was not persent
// so you will need to use an option
apples.get.isDefined
```

The point is, flag option is either `true` or `false` - what else could it be?

**Comment by alexy** [comment]
When I prefer the logic of Some/None to be available for opt[Boolean], I tried to provide default=None, which was disrespected.  At least that should override Some(false)!

**Comment by Rogach** [comment]
Ok, so I am completely lost on this one :)

The `default = None` setting means that user haven't provided any default value for the option.

In case of the flag option, there are two states - when flag was found in the arguments (Some(true))
and not found in the arguments (Some(false)). What should None mean in this case?

**Comment by Rogach** [comment]
And `default = None` is not disrespected, it is just that flag option is always defined (at least for the observer).
