### ISSUE TITLE
fileConverter should not force file to exist

### ISSUE THREAD

**Issue by jkinkead** [scallop/scallop#110]
`fileConverter` should not force the file to exist. It's common to want an argument to be a destination file. Ideally, the existance validation could be a separate function:

``` scala
implicit val fileConverter = stringConverter.map(new File(_))
def fileExists(f: File) = {
  if (f.exists) Right(Unit) else Left("file '%s' doesn't exist" format f)
}
val myConf = new ScallopConf(args) {
  val output = opt[File]("output")
  val input = opt[File]("input")
  validate(input)(fileExists)
}
```

**Comment by Rogach** [comment]
One big concern - that will be a breaking change (some users may depend on that behavior, removing it will break code). So we will have to bump major version to 2.x - seems a little bit excessive for such a small change, but okay.

About the actual implementation - maybe it will be nicer to create the following syntax?

``` scala
  validateFileExists(input) // calls validate(input)(fileExists) or similar internally
```

Seems a little cleaner than standalone validation function (which anyone can write anyway).

**Comment by jkinkead** [comment]
Yeah, it's too bad it's probably a breaking change.

I like the cleaner validation!

**Comment by Rogach** [comment]
Implemented the idea. If everything is looks okay to you, I will release the new version shortly.

**Comment by jkinkead** [comment]
File changes look great!

I use `java.nio.file.Path` in my application; would you mind waiting on a short PR to add a converter for that?
