### ISSUE TITLE
Feature request: ScallopOption to support getOrElse

### ISSUE THREAD

**Issue by delocalizer** [scallop/scallop#112]
It would be great to be able to write `option.getOrElse("foo")` instead of

```
option match {
  case None => "foo"
  case Some(x) => x
}
```

**Comment by Rogach** [comment]
Done. Also deprecated `.get` method and replaced it with `.toOption`, to avoid confusion with native scala Option.

Will release new version (probably 2.0.0) within several days.

**Comment by delocalizer** [comment]
Awesome, thanks for the fast turnaround!
