### ISSUE TITLE
Scala 2.12 final version

### ISSUE THREAD

**Issue by inkytonik** [scallop/scallop#120]
Would it be possible to publish Scallop for Scala 2.12 final (which is now on Maven)? Apart from the latest release of Scallop, I would be interested in having a 2.12 version of Scallop 1.0.0 if that is possible, since the published version of our library is based on 1.0.0.

**Comment by Rogach** [comment]
Thanks for a reminder!

Published `2.0.4` and `1.0.0` for Scala `2.12.0`, should sync to Maven Central within an hour.

**Comment by inkytonik** [comment]
Thanks!
