### ISSUE TITLE
More file validation

### ISSUE THREAD

**Issue by rvanheest** [scallop/scallop#121]
Hi, currently I'm in the process of upgrading from an old version of Scallop to 2.x in a couple of projects. Some of these projects rely on Java's `File` class and I especially enjoy the changes made to your library where you have to explicitly validate that the file exists!

Some of my projects, however, require for some alternative checks. These include:
 * validate that a `File` does not exist
 * validate that a `File` is a **directory**
 * validate that a `File` is a **file** 

Would you see value in adding checks like these to the Scallop library? If so, I'd be happy to contribute!

**Comment by Rogach** [comment]
Yes, those will definitely be helpful!

**Comment by rvanheest** [comment]
Here you go! See #122. LMKWYT

**Comment by Rogach** [comment]
LGTM. I'll release a new version with this changes shortly.

**Comment by rvanheest** [comment]
Great! One question about those releases that I already hit my head against a couple of times in various repositories: would you be able to give a brief release note in the description of your releases? In that way it is easier for users to see whether an update is worth the effort of upgrading given the content of the update. Currently users have to search through the repository's commit history to find out what changed. I always refer to [RxJava's release notes](https://github.com/ReactiveX/RxJava/releases) although that level of detail is not really necessary for the small diffs between releases of Scallop. A brief description might be nice though!

Thanks anyway. It was a pleasure to contribute.

**Comment by Rogach** [comment]
That would be a good idea - I'll read up on creating such release notes and will try to do it with this release.

**Comment by Rogach** [comment]
Here you go - `2.0.5` is released, should sync to Maven Central within an hour. And I created release notes for the latest two releases.

**Comment by rvanheest** [comment]
Mmm, not sure about this, but 19 hours later there is still no reference to this new version in https://mvnrepository.com/artifact/org.rogach/scallop_2.11. Am I missing something?

**Comment by Rogach** [comment]
Seems `mvnrepository` experiences some problems - the downloads are all in the repo: http://central.maven.org/maven2/org/rogach/scallop_2.11/2.0.5/

`search.maven.org` also lists the release: http://search.maven.org/#search|ga|1|scallop

**Comment by Rogach** [comment]
I double-checked, and SBT was capable of finding and downloading the `2.0.5` version just fine in one of my projects.

**Comment by rvanheest** [comment]
Thanks for the quick response. It all seems working on my side now as well! 👍
