### ISSUE TITLE
Problem ignoring exceptions

### ISSUE THREAD

**Issue by pacop** [scallop/scallop#123]
Hello, I am trying to ignore the exception UnknownOption, since I am providing more args (these additional args do not need to be parsed by Scallop). Is there some way of ignoring this exception, building a fully functional ScallopConf where unknown options were ignored?

**Comment by Rogach** [comment]
Currently unknown option exception will probably leave `ScallopConf` in inconsistent state, so you would not be able to access even those args that should have been parsed. It is probably possible to tweak it to work in such case, but it would not be easy.

Maybe we can do it in some alternative way?

You can provide all those options after `--`, thus putting them all in trailing args:

``` scala
val args = Seq("--input", "input", "--", "--test", "ignoreMe")
object Conf extends ScallopConf(args) {
  val input = opt[String](required = true)
  val ignored = trailArg[List[String]]()
}
Conf.input() shouldBe "input"
Conf.ignored() shouldBe Seq("--test", "ignoreMe")
```

Alternatively, you can remove unknown options before passing arguments into `ScallopConf`. Here's an example - I assumed that ignored options are all in long form and have a single arg:

``` scala
@annotation.tailrec
def filterOptions(
  args: List[String],
  filtered: List[String],
  ignored: List[String]
): (List[String], List[String]) = {
  val whitelist = List("--input", "--output", "--class")
  args match {
    case Nil => (filtered.reverse, ignored.reverse)
    case opt :: arg :: rest if opt.startsWith("--") && !whitelist.contains(opt) =>
      filterOptions(rest, filtered, arg :: opt :: ignored)
    case opt :: rest =>
      filterOptions(rest, opt :: filtered, ignored)
  }
}

val args = List("--input", "input", "--test", "ignoreMe", "--output", "output")
val (filtered, ignored) = filterOptions(args, Nil, Nil)
filtered shouldBe List("--input", "input", "--output", "output")
ignored shouldBe List("--test", "ignoreMe")
```
