### ISSUE TITLE
Using properties with comma values

### ISSUE THREAD

**Issue by rodzac** [scallop/scallop#125]
Hey guys,

I was creating a new App that uses Scallop for parsing the inputs, but I got stuck in this scenario, can you help me with it? It looks like that when one of the properties has a value that contains ',' (comma), the parser throws "wrong arguments format" exception. I implemented the following code to reproduce the problem. I'm using Scallop version 1.0.1.

**test**
 ```
class ScallopPropertiesTest extends FlatSpec with Matchers {

  class TestInput(args: Seq[String]) extends ScallopConf(args){
    val context = props[String]('C')
    verify()
  }

  "construtor" must "parse the args and return a context with two values" in {
    // setup
    val args = Array("-CpropA=2016-01-12", "-CpropB=1,2")

    // test
    var inputs = new TestInput(args)

    // verify
    inputs.context should have size 2
  }
}
```
**output**
[scallop] Error: Bad arguments for option 'C': 'propB='1,2'' - wrong arguments format

**Comment by Rogach** [comment]
It trips on the comma - property option parser expects comma-separated list of key-value pairs (#10). Original idea was that `=` and `,` can't be passed in property args.

I'm not sure how to properly handle this. Adding escapes (`\=`, `\,`) for these is going to be confusing for the user, trying to detect such situations automatically is going to be buggy and still won't solve the general problem. What's your opinion?

**Comment by rodzac** [comment]
I believe that something like `-CpropB="1,2"` is a great solution for it. When the parser found a quote or a double quote on the first char on the right side operator, it should eval the right side as a plain String. What do you think?

**Comment by Rogach** [comment]
But then the user will actually have to type ` '-CpropB="1,2"' ` or ` "-CpropB=\"1,2\"" ` on the command line, which is actually horrible.

**Comment by Rogach** [comment]
I think that using usual `\` escapes will be the most obvious way for the user: `-CpropB=1\\,2` or `'-CpropB=1\,2'`. I'll implement it today or tomorrow. Will that solve your problem?

**Comment by Rogach** [comment]
(and I'll improve error message in case user forgets to escape commas)

**Comment by rodzac** [comment]
I believe that the backslash will solve the problem, but I didn't understand why I should add the single quotes wrap on the examples (`'-CpropB="1,2"'`)? On my command line App, I'm just using something like `./my-app -C propA=AA propB=1,2`, and everything works fine.

**Comment by Rogach** [comment]
Without single quote wrap shell will parse double quotes and the application will never see them - here's an example with bash and `echo`:
```bash
$ echo a="b"
a=b
$ echo 'a="b"'
a="b"
```

**Comment by Rogach** [comment]
By the way, you can easily write your own props converter and replace the default one (here's the [default definition](https://github.com/scallop/scallop/blob/develop/src/main/scala/org.rogach.scallop/package.scala#L94)).

This way you would be able to get the exact semantics you need (for example, just get rid of the comma if you don't need it), since you are not burdened by backwards compatibility as I am.

**Comment by Rogach** [comment]
Released version `2.0.6` with comma and equals sign escaping, should sync to Maven Central within an hour.

**Comment by rodzac** [comment]
cool! thank you!

**Comment by kashifusmani** [comment]
I came up with this, for anyone interested



    val customConverter: ValueConverter[Map[String, String]] = new ValueConverter[Map[String, String]] 

    {

    def parse(s: List[(String, List[String])]): Either[String, Option[Map[String, String]]] = {
      
     val argsList = s.head._2

      if (argsList.size != 1) Left("Only 1 argument allowed")

      else {

        val splitted = argsList.head.split("=")

        if (splitted.size != 2) Left("Incorrect format")

        else Right(Some(Map(splitted.head -> splitted.last)))

      }

    }

    val tag = scala.reflect.runtime.universe.typeTag[Map[String, String]]

    val argType = org.rogach.scallop.ArgType.LIST

    }

and use it as 

`
    val source: ScallopOption[Map[String, String]] = opt[Map[String, String]](name = "key-vals", required = true,
    descr = "--key-vals key=val1,val2,val3"
  )(customConverter)
`
