### ISSUE TITLE
comparison with https://github.com/scopt/scopt

### ISSUE THREAD

**Issue by antonkulaga** [scallop/scallop#127]
I had a little bit of confusion between https://github.com/scopt/scopt and https://github.com/scallop/scallop as they have very similar names and solve the same problem. I originally thought that one if the fork of another. Maybe it would be nice to mention the different in README?

**Comment by Rogach** [comment]
No, we do not have any shared origin or shared code with scopt. It does solve the similar problem, but in a  different way.

Mentioning it in README will require creation and maintenance of list of all the available CLI parsing libs, which will be quite long and in my opinion unnecessary - and it is much better managed [elsewhere](https://www.google.ru/search?q=scala+command+line+parsing).
