### ISSUE TITLE
Testing for -h is throwing strange errors

### ISSUE THREAD

**Issue by hrj** [scallop/scallop#129]
Firstly, thanks for this useful library!

We have been using scallop in the [abandon](https://github.com/hrj/abandon/) project for a long time, and it works fine. But when we tried to add a test case for the "-h" option, we are getting strange errors from `scalatest`.

Please see [this PR](https://github.com/hrj/abandon/pull/128).

Any idea what's going on? Is the output stream being closed prematurely?

**Comment by Rogach** [comment]
I traced the error to this line: https://github.com/hrj/abandon/blob/master/base/src/main/scala/co/uproot/abandon/Config.scala#L19

`Help` and `Version` are not subclasses of `ScallopException`, they are subclasses of `ScallopResult`. So the match statement did not catch them, instead forwarding to `super.onError` - which prints help and calls `sys.exit(0)`, killing the forked process and closing the streams.

Adding separate catch clause for `Help` fixed the failing test. Also, if you want to retain default behavior for help and version, you should take a look at original implementation of `onError`: https://github.com/scallop/scallop/blob/develop/src/main/scala/org.rogach.scallop/ScallopConf.scala#L403

Alternative way will be to forbid `sys.exit` for the time of this test execution, as we do when testing scallop: https://github.com/scallop/scallop/blob/develop/src/test/scala/CapturingTest.scala#L24

By the way, your colleague is right - only `--help` is created by default, `-h` needs to be specified explicitly.

**Comment by hrj** [comment]
Thanks a lot for the detailed response. We will fixup the `onError` implementation in `abandon`. Closing this issue in the meanwhile.
