### ISSUE TITLE
report trailing parameters in --help, explain them in Conf

### ISSUE THREAD

**Issue by alexy** [scallop/scallop#13]
When trailing parameters are expected, it's important that --help says what they are.  In order to name them, let's allow descr for trailArg exactly for this purpose.

**Comment by Rogach** [comment]
Ok. I expected that it would be better to explain them in the banner section, but I can add it like this:

``` scala
val t = trailArg[Int](name = "total", descr = "some description")
```

Output:

```
// option info

Trailing arguments:

total (required)
    some description
```
