### ISSUE TITLE
scala-native crossbuild

### ISSUE THREAD

**Issue by oker1** [scallop/scallop#136]
I'd love to have a cli arg. parser for scala-native experiments, and this is my favorite one.

If you are interested/willing to support it I'll try to scrape together a PR of this. The project can compile with the native compiler, but I'm inexperienced with sbt so it's a bit of a wrestle to create a proper config.

**Comment by Rogach** [comment]
Yes, I will be interested!

**Comment by danielyli** [comment]
Hey, how's this going? I'd love to see scallop become the go-to CLI parser for Scala Native.

**Comment by Rogach** [comment]
@danielyli Hi! Sorry for the delay - I'll really hope to get to it this week.

**Comment by Rogach** [comment]
@danielyli - just to notify you - I finally got to the build for scala-native (#138). Turns out that it is not very easy and requires breaking changes to the library, but it is doable and I will probably finish it tomorrow.

**Comment by danielyli** [comment]
Awesome! Can't wait to try it out.

**Comment by Rogach** [comment]
Released version `3.0.0`, cross-built for Scala Native - should sync to Maven Central within an hour. Can you test it and confirm that it is working?

**Comment by Rogach** [comment]
Hit a huge bug - turns out that scala-native does not yet implement java.util.Formatter, and we depend on it everywhere in help and error printing (and it is replaced by unimplemented methods on link-time, which results in stuff breaking on run-time). I'll try replacing it with our custom implementation.

**Comment by Rogach** [comment]
Fixed `String.format` problems and couple of other bugs - should be working now. Released `3.0.1` version.

**Comment by danielyli** [comment]
Awesome. Will try it out when I get the chance!
