### ISSUE TITLE
You should show off more!

### ISSUE THREAD

**Issue by jhclark** [scallop/scallop#14]
I wondered if you could support lists of trailing options. In fact, you can do this in a very fancy way, as I found (a bit buried) in your blog post. Perhaps consider moving this to the main README? It's impressive.

``` scala
  .trailArg[String]("first list name")
  .trailArg[List[Int]]("first list values")
  .trailArg[String]("second list name")
  .trailArg[List[Double]]("second list values")
```

**Comment by Rogach** [comment]
Yes, it would be good :)

It was in README at some point, but then it got quite long and many parts were moved [into the wiki](https://github.com/Rogach/scallop/wiki).

I'll return it back right now.
