### ISSUE TITLE
Cross build for Scala JS

### ISSUE THREAD

**Issue by edude03** [scallop/scallop#141]
Hello, I'm using Scallop in a Scala CLI tool that I want to cross build for JS but unfortunately this library doesn't support ScalaJS. I was wondering as you're adding Scala-native support, if ScalaJS wouldn't be too much to ask? 

Thanks :)

**Comment by Rogach** [comment]
Implemented, released version `3.0.0` - should sync to Maven Central within an hour. Can you test in your project?

**Comment by Rogach** [comment]
Fixed a bug with no error output in ScalaJS build - released `3.0.1`.

**Comment by edude03** [comment]
Thanks @Rogach let me know how I can send you a beer :D 

I'm using 3.0.1 and I'm noticing the example in the read me doesn't work, if I don't name my args then I get a `$c_Lorg_rogach_scallop_exceptions_OptionNameGuessingFailure().init___()` error. 

For example this works

```scala
class Conf(arguments: Seq[String]) extends ScallopConf(arguments) {
  //val apples = opt[Int](required = true)
  val bananas = opt[Int]("bananas")
  //val name = trailArg[String]("name")
  verify()
}


def main(): Unit = {
    val conf = new Conf(Seq("--bananas", "0")) 
    println("bananas are: " + conf.bananas())
  }
```

This doesn't

```scala
class Conf(arguments: Seq[String]) extends ScallopConf(arguments) {
  val apples = opt[Int](required = true)
  val bananas = opt[Int]("bananas")
  //val name = trailArg[String]("name")
  verify()
}


def main(): Unit = {
    val conf = new Conf(Seq("--bananas", "0")) 
    println("bananas are: " + conf.bananas())
  }
```

Any ideas?

**Comment by Rogach** [comment]
ScalaJS does not have full java-style reflection support - and Scallop depends on at least `.getClass.getMethods` for option name guessing. (same problem is in Scala Native)

So for now there is no support for option name guessing in Scala JS version, sadly.

**Comment by edude03** [comment]
That's what I figured. That said, how do I make trailing args work then? Uncommenting that val name line seems to have the same issue (actually, I think it makes name required instead of naming the param)

**Comment by Rogach** [comment]
I tried the following, and it worked:
```scala
    val conf = new ScallopConf(List("-a","3", "some-name")) {
      val apples = opt[Int]("apples")
      val name = trailArg[String]("name")
      verify()
    }
    assert(conf.apples() == 3)
    assert(conf.name() == "some-name")
```
Trailing args are required by default - maybe that was the source of confusion?

**Comment by edude03** [comment]
Yeo sounds like it! Thanks @Rogach

**Comment by Rogach** [comment]
Great!

I think I'll be able to sidestep the reflection problem by using macros, but that is entirely separate story and I won't be able to do it right now (and requires dropping 2.10.x support).

Closing the issue for now.

**Comment by MasseGuillaume** [comment]
Added: https://github.com/scallop/scallop/wiki/Native-and-JS

Maybe the exception should point to this page?

**Comment by Rogach** [comment]
Yes, providing a better exception for Native and JS platforms is a good idea.
