### ISSUE TITLE
Output error messages to stderr (as well as stdout?)

### ISSUE THREAD

**Issue by benwing** [scallop/scallop#142]
Currently ScallopConf's default errorMessageHandler outputs its messages to stdout. This is unexpected, as errors should go to stderr. Can this be modified to output to stderr? For compatibility you might want to continue to send the messages to stdout as well. Thanks!

**Comment by Rogach** [comment]
Yes, I'll change the behavior to output to stderr. Since I released new major version just yesterday, I think I can even avoid incrementing the major version number.

**Comment by Rogach** [comment]
Will release `3.0.1` later today, once I'm done fixing problems with native compilation.

**Comment by Rogach** [comment]
Released `3.0.1` with this change, should sync to Maven Central within an hour.

**Comment by benwing** [comment]
Thanks! I'm importing 3.0.1 now.

**Comment by benwing** [comment]
I can't actually compile 3.0.1. I get this:

[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.scala-native:sbt-crossproject:0.1.0 -> 0.2.0
[warn] 	* org.scala-js:sbt-scalajs:0.6.16 -> 0.6.17

and then this:

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-native#nativelib_native0.3_2.10;0.3.0: not found
[warn] 	:: org.scala-native#javalib_native0.3_2.10;0.3.0: not found
[warn] 	:: org.scala-native#scalalib_native0.3_2.10;0.3.0: not found
[warn] 	:: org.scala-native#test-interface_native0.3_2.10;0.3.0: not found
[warn] 	:: org.scala-native#nscplugin_2.10.6;0.3.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 

Then I get 19 errors, of which the first few are as follows:

[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/CliOptions.scala:71: not found: value flagConverter
[error]     (if (converter == flagConverter) None else default().map(_.toString))  // we don't need to remind user of default flag value, do we?
[error]                       ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/Scallop.scala:72: not found: type ScallopArgListLoader
[error] ) extends ScallopArgListLoader {
[error]           ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/Scallop.scala:23: not found: value flagConverter
[error]       converter = flagConverter,
[error]                   ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/Scallop.scala:37: not found: value flagConverter
[error]       converter = flagConverter,
[error]                   ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/Scallop.scala:219: not found: value loadArgList
[error]   private lazy val parsed: ParseResult = parse(loadArgList(args))
[error]                                                ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/Scallop.scala:263: not found: value flagConverter
[error]       if (conv == flagConverter)
[error]                   ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/Scallop.scala:330: not found: value flagConverter
[error]       if (conv == flagConverter)
[error]                   ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/ScallopConfBase.scala:7: not found: type ScallopConf
[error] class Subcommand(commandNameAndAliases: String*) extends ScallopConf(Nil, commandNameAndAliases) {
[error]                                                          ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/ScallopConfBase.scala:7: too many arguments for constructor Object: ()Object
[error] class Subcommand(commandNameAndAliases: String*) extends ScallopConf(Nil, commandNameAndAliases) {
[error]                 ^
[error] /local/home/benjwing/devel/scallop-git/src/main/scala/org.rogach.scallop/ScallopConfBase.scala:10: not found: value editBuilder
[error]     editBuilder(_.copy(descr = d))
[error]     ^

Version 2.3.1 compiles fine.

If you need more info, just let me know.

**Comment by Rogach** [comment]
Are you compiling the project yourself instead of depending via maven?

You're probably using simple `sbt compile` on this project - that won't work, since we now cross-build for scala-native and scala-js. Try `jvm/compile`.

**Comment by benwing** [comment]
Thanks, that worked. However, 'sbt jvm/package' (or 'sbt jvm/compile') builds only for 2.12, and 'sbt "+ jvm/package"' builds only for 2.10. As it happens, this is currently OK for us because we are using Scala 2.10 in conjunction with Spark 1.6, but we'll be upgrading soon to Spark 2.0 and Scala 2.11. Also, you might want to document that you need to compile using jvm/compile; I had never heard of that until now.

**Comment by Rogach** [comment]
You can do `sbt "++2.11.11 jvm/compile"` to get it to select a specific version.

Yes, I'll document that in the wiki.

**Comment by benwing** [comment]
Thanks!

**Comment by benwing** [comment]
BTW, just wanted to say thank you for Scallop! We are using it now at Amazon for a large machine learning data pipeline with around 60-70 individual jobs. We switched recently from Scopt and deleted about 1,000 lines in the process.

**Comment by Rogach** [comment]
You're welcome!
