### ISSUE TITLE
You should show off even more!

### ISSUE THREAD

**Issue by aerskine** [scallop/scallop#15]
Thanks for scallop -- it fills a much needed gap!  Could it be published to the sonatype repo now that scala-tools.org is no more?

**Comment by Rogach** [comment]
Thanks for the suggestion!

Yes, I will open a request for sonatype repo publishing ASAP.

**Comment by Rogach** [comment]
Scallop is now published to Sonatype repository (starting from version 0.3.9). It would probably propagate to Maven Central in several hours, as well.

**Comment by aerskine** [comment]
Awesome...  Smart work!
