### ISSUE TITLE
improvement: `-h` for help?

### ISSUE THREAD

**Issue by fyears** [scallop/scallop#153]
Hi,

By generating help messages, scallop only generates `--help` automatically. Is it possible (or better) to also generate `-h` shortcut if there's no conflicts?

Similarly, how about also generating `-v` shortcut for `--version`?

**Comment by Rogach** [comment]
Yes, it is possible. I'll try to implement it this weekend.

**Comment by Rogach** [comment]
Yes, I'm hideously bad at estimating my available time :)

But I finally implemented the feature - released version `3.1.2`, should sync to Maven Central within an hour.
