### ISSUE TITLE
Passing log4j configuration params

### ISSUE THREAD

**Issue by ardlema** [scallop/scallop#154]
Hi there, first of all thank you for this awesome library. I'm using for a project and have the following question.

Apart from the "scallop" params I'd like to pass in a log4j external file to my java application but scallop, as it supposed, does not recognize the -Dlog4j.configuration=/path/to/log4j.xml param.

What would be the best approach to achieve this using the library?

Thank you in advance

**Comment by Rogach** [comment]
Hi!

You need to pass this argument in JVM arguments, instead of app arguments. For example, if you are launching your application using:

```bash
java -jar app.jar <app cli args>
```

You can add system property argument as follows:

```bash
java -Dlog4j.configuration=/path/to/log4j.xml -jar app.jar <app cli args>
```

**Comment by Rogach** [comment]
Hopefully my reply helped you with your problem, so I'm closing the issue. If you have additional questions, do not hesitate to reopen the issue.
