### ISSUE TITLE
Getting all options after the first trailArg as part of trailArg list?

### ISSUE THREAD

**Issue by jkarjala** [scallop/scallop#160]
I have a case where I'd need to get the options following first trailing arg as part of the trailing arguments list. Think something like unix "exec" which takes its own options, then an executable name and any number of options specific to that executable which should be passed to the executable without modification. 

I tried this: 
```
class LwpRunnerConfig(arguments: Seq[String]) extends ScallopConf(arguments) {
  banner("Usage: LWPRunner [options] processor command line")
  footer(
    """
      | Run the given processor command line reading input from inCatalog and writing to outCatalog.
    """.stripMargin)
  val inCatalog: ScallopOption[String] = opt[String](required = true, descr = "The input catalog or file or -")
  val outCatalog: ScallopOption[String] = opt[String](required = false, default = Some("-"), descr = "The output catalog HRN, or filename, or - for stdout")
  val command: ScallopOption[String] = trailArg[String](descr = "the processor executable")
  val parameters: ScallopOption[List[String]] = trailArg[List[String]](required = false, descr = "the processor arguments")
  verify()
}

```

When running ```LWPRunner  -i - cat -n```, where the "-n" should be passed to the "cat" executable, I get error "Unknown option 'n'", since scallops tries to parse it as LWPRunner option.

Is there any way to make the scallops config understand this case?

**Comment by Rogach** [comment]
Scallop supports POSIX `--` - all arguments after `--` are passed as-is to trailing args, so with slight modification your command would work:

```scala
LWPRunner -i input-catalog -- cat -n
```

Unfortunately, there is currently no built-in way to ignore "unknown option" errors.

**Comment by jkarjala** [comment]
That double dash option is good enough for my use case, thanks for the info.
