### ISSUE TITLE
Integration with spark-submit?

### ISSUE THREAD

**Issue by dclong** [scallop/scallop#168]
Scala is often used in Spark application. Is it possible to integrate scallop with spark-submit? If a Scala Object is intended to be used in Spark, is it possible to auto generated shell script wrapping both spark-submit options and the Scala Object's options automatically?

**Comment by Rogach** [comment]
I don't use Spark, unfortunately, so I am not fluent in specifics. Here's the excerpt from the docs:
```
./bin/spark-submit \
  --class <main-class> \
  --master <master-url> \
  --deploy-mode <deploy-mode> \
  --conf <key>=<value> \
  ... # other options
  <application-jar> \
  [application-arguments]
```

So I suspect that you can use Scallop without any problems - just append the options to the end:

```
./bin/spark-submit \
  --class <main-class> \
  # other spark options \
  <application-jar> \
  --option1 \
  --option2
```
If I am not correct, please give me a more specific example.

**Comment by ujjwal** [comment]
I use it routinely with Spark, it works fine. 

^ the above sample is correct.
