### ISSUE TITLE
arbitrary command

### ISSUE THREAD

**Issue by leobenkel** [scallop/scallop#169]
Is is possible to have something like `--<keyword>` which would automatically create a 
`conf.keyword` boolean type argument ? 
The same way we can have the `--<number>` but with strings.

**Comment by Rogach** [comment]
Unfortunately, no such functionality is present yet. It's a good idea, I can try implementing it, but I'm terribly short on time and so can't say when it will be done.

**Comment by leobenkel** [comment]
no problem ! Thanks !

**Comment by Rogach** [comment]
Hi! I thought about it, and I think such feature won't fit in Scallop very well. The very idea of Scallop is to parse the arguments as safely as possible ("static typing for cli"), and in my opinion introducing such "dynamic" options will hinder this goal. Also such options will basically disable error checking for all other options - Scallop will not be able to distinguish between mistyped option and dynamic one.
