### ISSUE TITLE
Disable automatic short option generation?

### ISSUE THREAD

**Issue by fancywriter** [scallop/scallop#173]
Hello!
I have a question. Support I have two different options which start from the same letter (support --port and --password, both start with **p**). In current implementation the one which is first will "take" **p** letter. Can I disable it? I want to disable it to avoid ambiguity.

Or another example, I want to generate automatic help for user which type either `-h` or `--help`, but at the same time I have option which also starts with *h* letter. What should I do?

**UPDATE:**  there is `noshort` parameter, didn't notice it from the first glance. Please add it to README.

**Comment by Rogach** [comment]
I think it would be hard to add all such small tricks to the README without cluttering it too much. Wiki and api docs do a better job at describing various parameters, I believe. But PR is always welcome, if you can find a non-intrusive way of adding this to README.
