### ISSUE TITLE
is it possible to have a list of valid values ? 

### ISSUE THREAD

**Issue by leobenkel** [scallop/scallop#176]
Something like:

``` 
val arg = opt[String](
required = false,
valids = List[String]("a", "b", "c")
)
```

and then when used anything beside `--arg a` `--arg b` `--arg c` will fail. Like `--arg d` would not work.

**Comment by leobenkel** [comment]
I found 

`validate = Seq("a", "b","c").contains,`

is that the correct way ?

**Comment by Rogach** [comment]
Yes, that will work.
