### ISSUE TITLE
ScallopOption.isSupplied throws an exception if the option is transformed and no name is explicitly given

### ISSUE THREAD

**Issue by LennartH** [scallop/scallop#178]
The following snippet throws an `UnknownOption` error with message `Unknown option '	1'`:
```scala
val config = new ScallopConf(Seq("-i", "5", "-l", "10")) {
  // Also tested with filter, filterNot and orElse
  // I assume all "transformation methods" cause the issue
  val index = opt[Int]().map(_-1)
  val length = opt[Int]()
  verify()
}
config.index.isSupplied
```
The error doesn't occur when an explicit name is given for the option.

This leads to the output `[scallop] Error: Unknown option '	1'` (from `ScallopConf`s error handling) when using `isSupplied` in the config validation:
```scala
val config = new ScallopConf(Seq("-i", "5", "-l", "10")) {
  val index = opt[Int]().map(_-1)
  val length = opt[Int]()
  addValidation {
    if (index.isSupplied && length.isSupplied && index() >= length()) {
      Left("Index out of bounds")
    } else Right(Unit)
  }
  verify()
}
println(config.summary)
```
This also means that the built-in validation methods (like `dependsOnAny`) can not be used unless explicit names are specified.

---

Side Note: The summary is printed with the original argument values (`index => 5`) and not the values after the transformations, but I can understand if this is intentional.

**Comment by Rogach** [comment]
Released `3.1.5` with the fix, please test the new version.

**Comment by Rogach** [comment]
Re Side Note - that's not exactly intentional, but an unfortunate side-product of the architecture. The only other option that I see would be to print several values per name ("index => 5, 4" in the example), since transformed options share the same name. And I think that will be even more confusing.

**Comment by LennartH** [comment]
It's working now. Thanks for the fix!

---

Is it possible to determine the order of the transformed options? This way you could print them in the summary like this `index => 5 -> 4`.

**Comment by Rogach** [comment]
Yes, in theory that could be possible, but quite hard to implement. There can be several options transformed from a single option, or several options transformed into single one with a for comprehension - we will need to handle and display a graph of those options.
