### ISSUE TITLE
the library dependency is not found

### ISSUE THREAD

**Issue by gmosx** [scallop/scallop#18]
I tried:

libraryDependencies += "org.rogach" %% "scallop" % "0.4.0"
libraryDependencies += "org.rogach" % "scallop" % "0.4.0"
libraryDependencies += "org.rogach" % "scallop_2.9.1" % "0.4.0"

but nothing works... I am using Scala 2.9.2 and hte latest sbt btw...

**Comment by Rogach** [comment]
Thanks for reporting this issue!

It seems that there were some problems when promoting that release in sonatype repo. 

Should work now.

**Comment by gmosx** [comment]
Thanks for the fix!
