### ISSUE TITLE
How to parse Map[String,String] ? 

### ISSUE THREAD

**Issue by leobenkel** [scallop/scallop#180]
Is it possible to have `opt[Map[String,String]]` and if yes, how do you use it ? 

```
--myCommand key value key value ...
```

or 

```
--mycommand key=value key=value ...
```

?? 

Thanks.

**Comment by Rogach** [comment]
Maybe property arguments will help? https://github.com/scallop/scallop/wiki/Option-types-and-definitions#property-arguments

**Comment by leobenkel** [comment]
I don't really understand how to use it tho. What is the difference with `opt[Map[String,String]]` ? 
And can I have a long name with `--` instead of a one letter thing ?

**Comment by Rogach** [comment]
`opt[Map[String,String]]` will probably also work, but autogenerated help output will be less obvious.

Yes, you can have a long name - `propsLong[String]("mycommand")`, for example.

**Comment by leobenkel** [comment]
Thanks I am going to try `propsLong`

**Edit:** 
`propsLong` do not have constructor with `required` or `default` . What are they going to be ? 
It also does not generate name properly

**Comment by Rogach** [comment]
Default is empty map (`Map()`). There is no mechanism to mark some of the properties as required.

About the name - yes, currently it requires the option name to be provided explicitly.

**Comment by leobenkel** [comment]
ok thanks.
