### ISSUE TITLE
Please publish a version for Scala 2.13.0-RC2

### ISSUE THREAD

**Issue by Sciss** [scallop/scallop#186]

**Comment by Rogach** [comment]
Unfortunately scallop depends on scalatest, and they haven't yet released a version for Scala `2.13.0-RC2` (https://github.com/scalatest/scalatest/issues/1586).

**Comment by Sciss** [comment]
Hi there. I saw scalatest entered Maven Central today: https://search.maven.org/artifact/org.scalatest/scalatest_2.13.0-RC2/3.1.0-SNAP11/bundle

**Comment by Rogach** [comment]
It is true. I used mvnrepository.com to check published versions, and it seems that they are a little outdated. I will release the new version now.

**Comment by Rogach** [comment]
Released version `3.2.0` for Scala `2.13.0-RC2`, should sync to Maven Central shortly.

**Comment by Sciss** [comment]
Thanks very much; BTW, nice code base!

**Comment by Rogach** [comment]
Thanks for your kind words :)
