### ISSUE TITLE
How are List options supposed to work?

### ISSUE THREAD

**Issue by Sciss** [scallop/scallop#188]
I'm migrating some code from scopt to scallop; I wonder about the following:

```scala
import org.rogach.scallop.{ScallopConf, ScallopOption => Opt}

object ScallopBug {
  def main(args: Array[String]): Unit = {
    val testArgs = "-r foo file1.mllt file2.mllt".split(' ').toList

    object p extends ScallopConf(testArgs) {
      val workspaces: Opt[List[java.io.File]] = trailArg(required = false, default = Some(Nil),
        descr = "Workspaces (.mllt directories) to open"
      )
      val autoRun: Opt[List[String]] = opt("auto-run", short = 'r', default = Some(Nil),
        descr = "Run object with given name from root folder's top level. Comma separated list for multiple objects."
      )

      verify()
    }

    println(s"workspaces: ${p.workspaces()}")
    println(s"autoRun   : ${p.autoRun()}")
  }
}
```

The output is:

```
workspaces: List()
autoRun   : List(foo, file1.mllt, file2.mllt)
```

scopt uses a different way for specifying multiple trailing args (`unbounded`), and when use a `List[A]` as option type, it assumes comma separation, like I would have to write

     "-r foo,bar file1.mllt file2.mllt"

Is the behaviour of scallop correct here; is there a way to support comma separated multi-arguments, or do I need to write my own converter for that?

**Comment by Sciss** [comment]
Here is my next idea:

```scala
      val autoRun: Opt[List[String]] = opt[String](default = Some(""),
        descr = "Comma separated list"
      ).map(_.split(',').toList)
```
WDYT?

**Comment by Rogach** [comment]
You were faster than me :) I was about to suggest the same thing. Only one caveat - I'd suggest filtering out empty strings, since `"".split(",").toList == List("")` (one-element list instead of empty list). Changing `.split(",")` to `.split(",").filter(_.nonEmpty)` should do the trick.

**Comment by Sciss** [comment]
Ok, thanks
