### ISSUE TITLE
Error with combine scallop and spark

### ISSUE THREAD

**Issue by ostronaut1** [scallop/scallop#195]
I have project where I use Spark and Scallop in same time. Previous I use only Scallop and it worked very nice. But now I have the following error when try start fat jar:
`Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
        at org.rogach.scallop.Scallop.<init>(Scallop.scala:61)
        at org.rogach.scallop.Scallop$.apply(Scallop.scala:13)
        at org.rogach.scallop.ScallopConf.<init>(ScallopConf.scala:50)
`

I use Grable to manage and build my project and here dependencies  what I use:

dependencies {
    // https://mvnrepository.com/artifact/org.scala-lang/scala-library
    compile group: 'org.scala-lang', name: 'scala-library', version: '2.12.8'

    // https://mvnrepository.com/artifact/org.apache.spark/spark-core
    compile group: 'org.apache.spark', name: 'spark-core_2.11', version: '2.4.3'
    // https://mvnrepository.com/artifact/org.apache.spark/spark-sql
    compile group: 'org.apache.spark', name: 'spark-sql_2.11', version: '2.4.3'
    // https://mvnrepository.com/artifact/org.apache.spark/spark-mllib
    compile group: 'org.apache.spark', name: 'spark-mllib_2.11', version: '2.4.3'
    // https://mvnrepository.com/artifact/org.apache.spark/spark-hive
    compile group: 'org.apache.spark', name: 'spark-hive_2.11', version: '2.4.3'

    // https://mvnrepository.com/artifact/com.typesafe/config
    compile group: 'com.typesafe', name: 'config', version: '1.2.1'

    // https://mvnrepository.com/artifact/org.rogach/scallop
    compile group: 'org.rogach', name: 'scallop_2.11', version: '3.0.1'

    // https://mvnrepository.com/artifact/com.sun.jersey/jersey-client
    compile group: 'com.sun.jersey', name: 'jersey-client', version: '1.9.1'

}

Thank you a lot for help!

**Comment by Rogach** [comment]
It seems that you include scala library 2.12.8 (`name: 'scala-library', version: '2.12.8'`), while using 2.11 libraries (`name: 'scallop_2.11', version: '3.0.1'`). Scala does  not keep binary compatibility between major releases (2.11 and 2.12 in this case). Can you try replacing scala version with `2.11.12`, maybe that will help?

**Comment by ostronaut1** [comment]
Yes, it is my bad(
Thank you a lot for your feedback and have a great day)

**Comment by Rogach** [comment]
You are welcome :)
