### ISSUE TITLE
Parse several subcommands simultaniously

### ISSUE THREAD

**Issue by ashkan-leo** [scallop/scallop#201]
Can you do this? Specifically, in the CLI, can I pass several subcommands (with the arguments they accept) to Scallop at the same time?
Currently I have defined several subcommands, and when I run my application if I provide only one of the subcommands everything works as expected.
However if I provide multiple subcommands, Scallop fails to parse the arguments.

```scala
class Config(args: Seq[String]) extends ScallopConf(args) {
  val param1 = opt[String](descr="param1")
  
  val sub1 = new Subcommand("sub1") {
    val param11 = opt[String](descr="param11")
    val param12 = opt[String](descr="param12")
  }
  val sub2 = new Subcommand("sub2") {
    val param21 = opt[String](descr="param21", default="x")
    val param22 = opt[String](descr="param22", default="y")
  }
  val sub3 = new Subcommand("sub3") {
    val param31 = opt[String](descr="param31")
    val param32 = opt[String](descr="param32")
  }
}
```

When I do `sbt run --param1 blah sub1 --param11 blah1 --param12 blah2 sub2 sub3 --param31 blah3 --param32 blah4`, I get the error:
```
[scallop] Error: Bad arguments for option 'param12': 'blah2 sub2 sub3' - you should provide exactly one argument for this option
```

What I'm doing wrong here?

**Comment by Rogach** [comment]
No, unfortunately Scallop only supports parsing one one subcommand at a time.

**Comment by ashkan-leo** [comment]
I think it would be a nice functionality to have.

**Comment by DonDebonair** [comment]
I don't think you should do this. It's completely ambiguous whether `sub2` in this example is an argument for `sub1` or another subcommand. You'll do the users of your application no favour in terms of usability, if you do this @ashkan-leo ;)

**Comment by Rogach** [comment]
At the moment I don't see a way to implement such feature in a maintainable way. As said above, resolving the ambiguity will be very difficult (maybe not impossible - but even if possible it will be sure to introduce lots of complexity and unobvious behavior).

If you have a strategy for reliably splitting the arguments into several sub-lists of different commands then you can do that before passing arguments into Scallop. For example, we can select `;` character to separate different portions of our commands as follows:

```scala
// in bash:
// $ program touch a \; cp a b \; rm a
val args = Seq("touch", "a", ";", "cp", "a", "b", ";", "rm", "a")

class Conf(args: Seq[String]) extends ScallopConf(args) {
  addSubcommand(new Touch)
  addSubcommand(new Copy)
  addSubcommand(new Remove)
  verify()
}
class Touch extends Subcommand("touch") {
  val filename = trailArg[String]()
}
class Copy extends Subcommand("cp") {
  val src = trailArg[String]()
  val dst = trailArg[String]()
}
class Remove extends Subcommand("rm") {
  val target = trailArg[String]()
}

@annotation.tailrec
def splitBySeparator(args: Seq[String], separator: String, acc: List[Seq[String]] = Nil): Seq[Seq[String]] = {
  if (args.isEmpty) acc.reverse
  else {
    val (commandArgs, restArgs) = args.span(_ != separator)
    splitBySeparator(restArgs.drop(1), separator, commandArgs :: acc)
  }
}

splitBySeparator(args, ";").foreach { commandArgs =>
  val conf = new Conf(commandArgs)
  conf.subcommand match {
    case Some(touch: Touch) =>
      println(("touch", touch.filename()))
    case Some(cp: Copy) =>
      println(("cp", cp.src(), cp.dst()))
    case Some(rm: Remove) =>
      println(("rm", rm.target()))
    case _ =>
  }
}
```
