### ISSUE TITLE
Error downloading org.rogach:scallop_sjs1_2.13:3.4.0

### ISSUE THREAD

**Issue by srubietodd** [scallop/scallop#204]
Hi, I have a Scala.js project which will run on Node.js and I would like to use Scallop.

- Scala 2.13.1
- SBT v1.3.9
- Scala.js v1.0.1

- libraryDependencies += "org.rogach" %%% "scallop" % "3.4.0"

I am using a Nexus proxy repo.

SBT update gives the error:

``[error] (jstest / update) sbt.librarymanagement.ResolveException: Error downloading org.rogach:scallop_sjs1_2.13:3.4.0``

``[error]   not found: https://nexus.dev.corkscrew.local:8546/repository/maven-central/org/rogach/scallop_sjs1_2.13/3.4.0/scallop_sjs1_2.13-3.4.0.pom``

I checked on maven central and the only SJS version for 3.4.0 is called "scallop_sjs0.6_2.12".

How do I use this in my SBT project or is it possible to publish a version for Scala.js 1 on Scala 2.13?

Regards

Steve

**Comment by Rogach** [comment]
I'll try building Scallop for Scala.js v1 tomorrow. However right now it gives me linking errors like "Referring to non-existent method static java.lang.System.exit(int)void". Any idea what should I use instead on Scala.js?

**Comment by srubietodd** [comment]
I think the scala.js team have removed VM specific methods such as System.exit.

Node has a "Process.exit()" which is what is needed.

I found a Scala.js facade library [here](https://github.com/scalajs-io/nodejs) for Node.js.  Only issue is the github for this facade library v0.4.2 is three years old and supports Node.js v8.7.0, now Node is at V12.13.0.

Another project [ScalablyType](https://github.com/ScalablyTyped/Distribution) provides many facade libraries for the Scala.js community, the one we need is called "node". 

I have not had time to try and use this yet, but it looks the better option.

**Comment by Rogach** [comment]
I feel that pulling in a huge facade dependency for a single call is not justified. Instead I simply used `process.exit` directly:
https://github.com/scallop/scallop/blob/develop/js/src/main/scala/org.rogach.scallop/Compat.scala#L6

**Comment by Rogach** [comment]
Released `3.4.0` for Scalajs 1.0 (for Scala 2.12 and 2.13). Closing the issue, feel free to reopen if any additional problems arise.

**Comment by srubietodd** [comment]
Many thanks for your prompt help and the useful tip about js.Dynamic.
