### ISSUE TITLE
[Question] is it possible to accept exactly only two values ?

### ISSUE THREAD

**Issue by leobenkel** [scallop/scallop#205]
I would like a `opt[(Int, Int)]` , is it built-in ? I can write my own parser of course. I was just curious if there were a nicer way to handle it with built-in features. 

Thanks !

**Comment by Rogach** [comment]
No, there is no built-in method for this. Unfortunately I won't be able to implement this myself in near future, but if you wish you can make a PR with this feature.

**Comment by leobenkel** [comment]
no worries :) I implemented a quick parser
