### ISSUE TITLE
Specific Command Line logic

### ISSUE THREAD

**Issue by jasonwebb2455** [scallop/scallop#208]
I'm using this library to try to parse command lines for some custom text tokenization in Apache spark with scala. I'm curious if some certain functionality is supported with the command line parsing in scallop. Let's say I want to be able to optionally supply a text file which lists other characters that I can split the text on other than whitespace. I want there to be a command line argument like --custom which will tell me if there is a custom text file of characters to split on (so it's a boolean). If that argument is supplied then I want there to be a required argument called --customFile which will specify what the text file is called. I've been trying to see if I can do this with subcommands.

I realize that I could just have an optional argument called --customFile by itself, but I'm unsure about how to check if it's actually supplied by the user/client. I see that it's a ScallopNone object when I try to access it in the conf, but that a little informal and I actually don't even know if I can do something like:

if (conf.customFile != ScallopNone)

which is why I've been thinking about doing the --custom Boolean first then a required sub-argument for that.

**Comment by Rogach** [comment]
You can check if the user supplied the option by calling `.isSupplied`, for example:

```scala
if (conf.customFile.isSupplied) {
  // do stuff
```

Or convert the Scallop Option to Scala Option:
```scala
conf.customFile.toOption.foreach { file =>
```

I'll be closing the issue, feel free to reopen if you have more questions!
