### ISSUE TITLE
Error with subcommands?

### ISSUE THREAD

**Issue by jasonwebb2455** [scallop/scallop#210]
I'm getting an interesting error and I don't know quite what is it. I'm trying to do text processing with different stages and things by using Subcommands in scallop. Each text processing stage is a subcommand. 

Here is my configuration for the project:
```
import org.rogach.scallop._

class PreProcessingPipelineConf(args: Array[String]) extends ScallopConf(args) {

  val removeReplace = new Subcommand("removeReplace") {

    //input column of text to remove/replace on
    val inputCol = opt[String]("inputCol", required=true)

    //output column that has had the remove/replace performed on it
    val outputCol = opt[String]("outputCol", required=true)

    // If replacing punctuation in the text
    val replacePunct = opt[Boolean](name="replacePunct")

    // What to replace the punctuation with
    val replacePunctWith =opt[String](name="replacePunctWith")

    // String to specify the custom replacements, will be a regex expression probably
    val replaceCustom = opt[String](name="replaceCustom")

    // What to replace the custom strings with
    val replaceCustomWith = opt[String](name="replaceCustomWith")

  }
  addSubcommand(removeReplace)

  val lowerCase = new Subcommand("lowerCase") {

    //input column of text to send to lower case
    val inputCol = opt[String]("inputCol", required=true)

    //the column that has the lower case text
    val outputCol = opt[String]("outputCol", required=true)

  }
  addSubcommand(lowerCase)

  val tokenization = new Subcommand("tokenization") {

    // input columnd of text to tokenize
    val inputCol = opt[String]("inputCol", required=true)

    // the column that will have the tokenized text
    val outputCol = opt[String]("outputCol", required=true)

    //specifies if should split on whitespace or not
    val whitespace = opt[Boolean](name="whitespace")

    //specifies if should split on all non alpha numeric characters
    val nonAlphaNumeric = opt[Boolean](name="nonAlphaNumeric")

    //specifies the custom txt file of characters to split on
    val customFile = opt[String](name="customFile")

  }
  addSubcommand(tokenization)

  val stopWordRemover = new Subcommand("stopWordRemover") {

    // input column for the node to remove stop words from
    // should be ArrayType[StringType]
    val inputCol = opt[String](name="inputCol", required=true)

    // output column for the node to send the stop word removed text
    val outputCol = opt[String](name="outputCol", required=true)

    // indicates if the default stop words file will be used
    val defaultStopWords = opt[Boolean](name="defaultStopWords")

    // indicates if there is a custom stop word list to be used and provides the name of the file
    // as the string
    val customStopWords = opt[String](name="customStopWords")

    // indicates if the default stop words should all be lower case or should be kept case sensitive
    // true means they should all be sent to lowercase
    val lowerCase = opt[Boolean](name="lowerCase")

    // indicates if the default stop words should have punctuation in them
    val withoutPunct = opt[Boolean](name="withoutPunct")

  }
  addSubcommand(tokenization)

  verify()

}
```
And when I give it the following command line args:
`removeReplace --inputCol review --outputCol removed --replacePunct lowerCase --inputCol removed --outputCol lowered tokenization --inputCol lowered --outputCol tokenized --whitespace stopWordRemover --inputCol tokenized --outputCol removedStop --defaultStopWords --customStopWords customStopwords.txt`

I get the following error:
`[scallop] Error: Unknown option 'whitespace'`

I've also noticed that the Subcommands are not optional or it didn't seem to work when I just did:
`removeReplace --inputCol review --outputCol removed --replacePunct`

**Comment by jasonwebb2455** [comment]
I think it might have something to do with the fact that --whitespace is a boolean argument and in order to set it to true I just say --whitespace without an argument. So then it's taking stopWordRemover as the argument to --whitespace when it's not. But I try to do --whitespace true or just rearranging the args and that doesn't fix it

**Comment by Rogach** [comment]
The issue is due to the fact that Scallop doesn't support parsing multiple subcommands at the same level (see for example #201). It may be possible to implement something like that, but that would introduce ambiguity and the parser doesn't support that at the moment.

E. g. for example when you use git the following doesn't make sense: `git merge commit ...`

In your particular case I personally would have used the two-step approach: first split the arguments into several pipeline items (name+options) and then fed it into separate ScallopConf for each. But I'm not sure about the best way to handle ambiguities in such cases (for example what should happen if `tokenization` is the name of some column?). And you'll need some plumbing to aggregate help output from multiple such ScallopConfs.

**Comment by jasonwebb2455** [comment]
Thanks for the quick reply!! I'll probably just take in a json file and then map each command line args to the specific conf like you were saying. Something along the lines of:

`
{ "removeReplace" : {"--inputCol review --outputCol removed --replacePunct" },
  "lowerCase": {"--inputCol removed --outputCol lowered"},
...
}
`
Seems like it would be the easiest way to have "optional subcommands" and to parse them without the ambiguities you mentioned. There will be a separate conf file for each json entry

**Comment by Rogach** [comment]
Yes, json file will be a better approach in this case. But I think that placing args strings inside the file will be a little non-intuitive. I would have went further and just put all the args into JSON objects:
```
{ 
  "removeReplace": { "inputCol": "review", "outputCol": "removed", "replacePunct": true },
  "lowerCase": { "inputCol": "removed", "outputCol": "lowered" }
}
```
Also you will have more flexibility later with this approach - for example if you would add more complex transformations.
