### ISSUE TITLE
Way to make scallop throw exception with stake trace on error

### ISSUE THREAD

**Issue by samthebest** [scallop/scallop#211]
Typically when a mistake is made we get an error like:

```
[scallop] Error: Excess arguments provided: '30000'
```

Sometimes this happens in unit tests, and it kills the process, then it's hard to figure out where this error came from.

Is there a way to create an ScallopConf class, or modify the behaviour of `verify` so that it will also print a stack trace?

**Comment by Rogach** [comment]
Yes, you can try setting `throwError` to true:
```scala
org.rogach.scallop.throwError.value = true
```

**Comment by samthebest** [comment]
Thanks @Rogach  that works, and now I get exceptions, but I can't now use -h, I get:

```
Exception in thread "main" org.rogach.scallop.exceptions.Help
	at org.rogach.scallop.Scallop.verify(Scallop.scala:604)
	at org.rogach.scallop.ScallopConfBase.verifyBuilder(ScallopConfBase.scala:405)
	at org.rogach.scallop.ScallopConfBase.verify(ScallopConfBase.scala:831)
	at ops_tool.subcommands.JobOpts.<init>(OpsToolCommands.scala:71)
	at ops_tool.subcommands.OpsToolCommands$.$anonfun$subCommands$43(OpsToolCommands.scala:352)
	at ops_tool.OpsTool$.main(OpsTool.scala:130)
	at ops_tool.OpsTool.main(OpsTool.scala)
```

**Comment by Rogach** [comment]
If you need this for unit testing, you can just set it at the beginning of a test - it's a global thread-local variable ([example](https://github.com/scallop/scallop/blob/develop/jvm/src/test/scala/SubcommandsTest.scala#L8)). This way in the release build you will be able to use `--help` and `--version` as usual.

If you need more fine-grained control (for example if you need to tweak the behavior in a release build), you can override `ScallopConf.onError` method. Here's what we do by default: https://github.com/scallop/scallop/blob/develop/src/main/scala/org.rogach.scallop/ScallopConfBase.scala#L454

**Comment by samthebest** [comment]
For future copy and paste needs:

```
abstract class VerboseFailScallop(arguments: Seq[String]) extends ScallopConf(arguments) {
  override def onError(e: Throwable): Unit = e match {
    case r: ScallopResult if !throwError.value => r match {
      case Help("") =>
        builder.printHelp
        sys.exit(0)
      case Help(subname) =>
        builder.findSubbuilder(subname).get.printHelp
        sys.exit(0)
      case Version =>
        builder.vers.foreach(println)
        sys.exit(0)
      case e@ScallopException(message) =>
        // We want to see stacktrace so it's easier to understand where in the code this ScallopConf is
        e.printStackTrace()
        errorMessageHandler(message)
    }
    case e => throw e
  }
}
```
