### ISSUE TITLE
isoforms reduction

### ISSUE THREAD

**Issue by mictadlo** [scallop/scallop#213]
Hi,
Scallop has done a really good job. I used the Scallop results with TransDecoder. Next, I would like to reduce the number of isoforms per gene. I noticed that not always the first isoform is the best one compared to the RNA-Seq profile as could be seen below a few examples:

1.
![Screen Shot 2020-08-22 at 4 35 26 PM](https://user-images.githubusercontent.com/588297/90951101-e1a4ec80-e49a-11ea-8d9d-beea34a26d5e.png)

2. 
![Screen Shot 2020-08-22 at 4 38 45 PM](https://user-images.githubusercontent.com/588297/90951106-e9fd2780-e49a-11ea-85ce-6082a39bd110.png)

3.
![Screen Shot 2020-08-22 at 4 51 37 PM](https://user-images.githubusercontent.com/588297/90951109-f41f2600-e49a-11ea-86c4-b61c63a2466d.png)

4. 
![Screen Shot 2020-08-22 at 4 58 42 PM](https://user-images.githubusercontent.com/588297/90951113-000ae800-e49b-11ea-85a4-077c77a9d2e3.png)

5.
![Screen Shot 2020-08-22 at 5 04 34 PM](https://user-images.githubusercontent.com/588297/90951118-07ca8c80-e49b-11ea-80ac-421c3f85ca98.png)

By any chance, is there a way to keep only the best isoform?

Thank you in advance,

Michal

**Comment by Rogach** [comment]
Hi! I suspect you opened an issue in the wrong repository - this Scallop is a command-line argument parser, not a transcript assembler. You probably meant this one: https://github.com/Kingsford-Group/scallop

**Comment by mictadlo** [comment]
oops, thank you.
