### ISSUE TITLE
Please add and publish version for Dotty

### ISSUE THREAD

**Issue by Sciss** [scallop/scallop#214]
Currently "released" dotty version is 0.27.0-RC1. In general requires adding sbt plugin

    addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.2") 

and then add `"0.27.0-RC1"` to `crossScalaVersions`. (I don't know how this plays with sjs and sn though).

**Comment by Rogach** [comment]
Done, released version `3.5.1`. However I wasn't able to run ScalaTest on it - but hopefully there are no additional problems.
