### ISSUE TITLE
Please publish for Dotty 3.0.0-M2

### ISSUE THREAD

**Issue by Sciss** [scallop/scallop#215]
thanks! In plugins, you need to update to

    addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.6")

for that to work.

**Comment by Sciss** [comment]
(I'm working on a PR)

**Comment by Rogach** [comment]
Released in version `4.0.0` (sorry for taking so long, had a lot of small breaking changes that needed to get in before the major version bump).

Unfortunately I wasn't able to find a way to generate docs via scaladoc from Scala 3 - either it drops with an error or output directoy is empty. Absense of documentation on new scaladoc doesn't help either. Hopefully this will improve by the time of the final Scala 3 release, in the meantime docs are published using 2.13.4.
