### ISSUE TITLE
Support snake case to camel case conversion

### ISSUE THREAD

**Issue by esafak** [scallop/scallop#219]
The [tests say snake case conversion is supported](https://github.com/scallop/scallop/blob/792b551ce342e02ef54417b0c4fad773dd55c89e/jvm/src/test/scala/OptionNameGuessing.scala#L45), but the test case is actually [kebab case](https://stackoverflow.com/questions/11273282/whats-the-name-for-hyphen-separated-case); a snake case argument with an underscore is not automatically converted to camel case.

**Comment by Rogach** [comment]
The linked test talks about camelCase, not snakeCase. And conversion here is not about converting `--opt_name` into `--opt-name`, it is about converting `val optName` into `--opt-name` when explicit option name is not provided.

Kebab-case is preferred for options, see for example [GNU style guide](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) or [this discussion](https://stackoverflow.com/questions/1253679/should-command-line-options-in-posix-style-operating-systems-be-underscore-style).

If you still need to use `--snake_case` option names, then you can provide the option name explicitly:

```scala
object Conf extends ScallopConf(Seq("--opt_name", "1")) {
  val optName = opt[Int]("opt_name")
  verify()
}
Conf.optName() shouldBe 1
```

Or you can use snake_case in your Scala identifiers as well:

```scala
object Conf extends ScallopConf(Seq("--opt_name", "1")) {
  val opt_name = opt[Int]()
  verify()
}
Conf.opt_name() shouldBe 1
```
