### ISSUE TITLE
Descr with newline looks ugly

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [scallop/scallop#231]
source:
```scala
val outputDir: ScallopOption[File] =
  opt(
    required = true,
    descr = "Directory to output generated files in\nIn same tree structure as inputDir",
  )
```
output:
```
  -o, --output-dir  <arg>         Directory to output generated files in
In same tree structure as inputDir
```
desired-output:
```
  -o, --output-dir  <arg>         Directory to output generated files in
                                  In same tree structure as inputDir
```

Also, it would realistically be nice to have `descr` be a list, but just having it line up properly with newlines would be nice.  
I would imagine it is probably as simple as desc.replaceAll("\n", "\n$stuffOnTheLeft").
It also does the same weird shifting left if it wraps. That should be indented as well.

**Comment by Rogach** [comment]
Released in version `4.0.4`. Thank you for the issue and the PR!
