### ISSUE TITLE
`--help` should take precedence

### ISSUE THREAD

**Issue by hcannoodt** [scallop/scallop#239]
Let's assume this scenario: a user of our program wants to execute an advanced command. The user starts to type the command and adds the first argument:

```
prog --arg value
```

Then, the user would like to apply a second argument, but does not remember it. So, the user adds `--help` at the end in order to easily remove it afterwards

```
prog --arg value --help
```

However, the result is that the command gets executed instead of showing the usage information.
We would think that `--help` is never ignored.

Simply checking for the presence of `--help` or `-h` is not preferable either as it doesn't account for the possibility of the (unlikely) event of having an argument that requires the value to be set to e.g. `--help`. I assume this might have been the reasoning for the current implementation.

In this scenario, argument `arg` would get the value `--help`.
```
prog --arg --help
```

**Comment by Rogach** [comment]
> In this scenario, argument arg would get the value --help.
> prog --arg --help

No,  this won't work. In this scenario an error would be thrown because of incorrect format of argument passed to `--arg`. Scallop doesn't allow passing arguments starting with `--` into the options, because that would make it impossible to output sane errors for cases when user genuinely fogot that an argument is needed.

**Comment by Rogach** [comment]
My analysis was incorrect. `--opt --help` indeed accepts "--help" verbatim, but only if `--opt` is a single-arg option. For flags or multi-arg options it will throw an error.

**Comment by Rogach** [comment]
Fixed the issue, will release a new version soon.

**Comment by hcannoodt** [comment]
Awesome! Thanks!
