### ISSUE TITLE
Simple Command Line Example

### ISSUE THREAD

**Issue by 3goats** [scallop/scallop#24]
Hi,

This is not really an issue as such, but I don't know where best to ask this question.

I'm new to Scala and I'm trying to get the following example working from the command line:-

``` scala
    object cmdlinetest {
      def main(args: Array[String]) {
        println("Hello, world!")

        import org.rogach.scallop._;

        val opts = Scallop(List("-d","--num-limbs","1"))
          .version("test 1.2.3 (c) 2012 Mr Placeholder")
          .banner("""Usage: test [OPTION]... [pet-name]
                    |test is an awesome program, which does something funny
                    |Options:
                    |""".stripMargin)
          .footer("\nFor all other tricks, consult the documentation!")
          .opt[Boolean]("donkey", descr = "use donkey mode")
          .opt("monkeys", default = Some(2), short = 'm')
          .opt[Int]("num-limbs", 'k',
          "number of libms", required = true)
          .opt[List[Double]]("params")
          .opt[String]("debug", hidden = true)
          .props[String]('D',"some key-value pairs")
          // you can add parameters a bit later
          .args(List("-Dalpha=1","-D","betta=2","gamma=3", "Pigeon"))
          .trailArg[String]("pet name")
          .verify

        println(opts.help)

      }
    }
```

Whats the best way to bind the options into the main method here?

Carlskii

**Comment by Rogach** [comment]
In the above example, the simplest way would be to instantiate Scallop with arguments:

``` scala
val opts = Scallop(args)
  // the rest of initialization
```

Even better would be to use ScallopConf - the result would be much shorter and less verbose:

``` scala
object cmdlinetest {
  def main(args: Array[String]) {
    println("Hello, world!")

    import org.rogach.scallop._;

    val opts = new ScallopConf(args) {
      guessOptionName = true
      version("test 1.2.3 (c) 2012 Mr Placeholder")
      banner("""Usage: test [OPTION]... [pet-name]
                |test is an awesome program, which does something funny
                |Options:
                |""".stripMargin)
      footer("\nFor all other tricks, consult the documentation!")
      val donkey = opt[Boolean]("donkey", descr = "use donkey mode")
      val monkeys = opt("monkeys", default = Some(2), short = 'm')
      val numberOfLimbs = opt[Int]("num-limbs", 'k', "number of limbs", required = true)
      val params = opt[List[Double]]("params")
      val debug = opt[String]("debug", hidden = true)
      val poperties = props[String]('D',"some key-value pairs")
      val petName = trailArg[String]("pet-name", descr = "pet name")
    }

    println(opts.numberOfLimbs())
  }
}
```

As for your original question, I think that using ScallopConf would be a bit better (the following is a self-contained example, you can compile and run it:

``` scala
import org.rogach.scallop._

object Main extends App {
  val opts = new ScallopConf(args) {
    banner("""
NDE/SCEP Certificate enrollment prototype

Example: java -jar demo.jar --dn CN=Test --nde-url http://www.example.com --password password

For usage see below:
    """)

    val ndeUrl = opt[String]("nde-url")
    val password = opt[String]("password", descr = "set the password")
    val capi = toggle("capi", prefix = "no-", descrYes = "enable adding to Windows key-store", descrNo = "disable adding to Windows key-store")
    val version = opt[Boolean]("version", noshort = true, descr = "Print version")
    val help = opt[Boolean]("help", noshort = true, descr = "Show this message")

  }

  println(opts.password())
}
```

It prints the following:

```
$ java -jar demo.jar --help

NDE/SCEP Certificate enrollment prototype

Example: java -jar demo.jar --dn CN=Test --nde-url http://www.example.com --password password

For usage see below:

  -c, --capi              enable adding to Windows key-store 
      --no-capi           disable adding to Windows key-store 
      --help              Show this message 
  -n, --nde-url  <arg>     
  -p, --password  <arg>   set the password 
      --version           Print version 
```

I'm not sure that I got the "capi" part right.

**Comment by 3goats** [comment]
Sorry for all the edits - Thank you very much this makes much more sense now!

However, if I run the second example without any options it doesn't return any of the required options as I would have expected.

e.g. 

``` javascript

> run
[info] Running Main 
[success] Total time: 0 s, completed 25-Oct-2012 07:47:12

```

also  if I enter an invalid option it returns a non zero exit code. e.g.

``` javascript

run --fd 
[info] Running Main --fd
[scallop] Error: Unknown option 'fd'
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 0 s, completed 25-Oct-2012 07:47:48

```

Its probably missing something but any pointers would be much appreciated!

**Comment by Rogach** [comment]
In your first two examples, the problem is that you call

```
run num-limbs 9
```

instead of

```
run --num-limbs 9
```

(if you leave out "--" before option name, it gets parsed as a trailing argument, and the parse fails)

If you want to display help output to user after error message, you can try this:

``` scala
... new ScallopConf(args) {
  // option definitions
  override def onError(e: Throwable) = e match {
    case ScallopException(message) =>
      println(message)
      printHelp
    case ex => super.onError(ex)
  }
}
```

In case of your third example (plain `run`), you should note that I didn't mark `password` option with `required` attribute, so when you call

```
opts.password()
```

it throws an exception (None.get). In this case, you should either mark the option with `required`:

```
val password = opt[String]("password", required = true)
```

or get the option value as `scala.Option`:

```
opts.password.get // None: Option[String]
```

As per the last problem (with `run --password`), that's my bug - parser expects the value to be provided after "--password", and in this case that value is missing. I'll fix it ASAP - the parser would throw WrongOptionFormat exception, and display message to the user.

**Comment by Rogach** [comment]
Fix pushed (1f495b1015). I'll release version `0.6.2` now, it would be available in about 2 hours (sync to Maven Central is slooow).

**Comment by 3goats** [comment]
Thanks very much

**Comment by 3goats** [comment]
Hi,

Thanks that worked great! One issue though I'm getting an issue with the printHelp method in the following code:-

``` scala

object Main extends App {
  val opts = new ScallopConf(args) {
    banner("""
NDE/SCEP Certificate enrollment prototype

Example: java -jar demo.jar --dn CN=Test --nde-url http://www.example.com --password password

For usage see below:
           """)

    val ndeUrl = opt[String]("nde-url")
    val password = opt[String]("password", descr = "set the password", required = true)
    val capi = toggle("capi", prefix = "no-", descrYes = "enable adding to Windows key-store", descrNo = "disable adding to Windows key-store")
    val version = opt[Boolean]("version", noshort = true, descr = "Print version")
    val help = opt[Boolean]("help", noshort = true, descr = "Show this message")

     override def onError(e: Throwable) = e match {
      case ScallopException(message) =>
        println(message)
        printHelp
      case ex => super.onError(ex)
    }
```

```
[error] /Users/CarlBourne/scala-project/src/main/scala/org/carlskii/test.scala:25: object printHelp is not a member of package org.rogach.scallop
[error]         scallop.printHelp
```

Regards,

Carl

**Comment by Rogach** [comment]
Try adding `sys.exit(1)` after `printHelp`.

**Comment by 3goats** [comment]
Perfect that did the trick! - As you can probably tell, I'm new to Scala and trying to get my head round the synax. Have nearly switched back to JRuby several times in the process so far. I'm still persevering though in the hope that Scala will bring many benefits to using the JVM.

Would you be so as to explain exactly what the `override` code block is doing?

Regards,

Carl

**Comment by Rogach** [comment]
In default ScallopConf, onError catches all errors, thrown by the parser, displays the message to user, and then exits.

When you are saying `new ScallopConf`, you are essentially defining new anonymous subclass of ScallopConf.

You needed to display help on error as well, so you overrided implementation of `onError` in ScallopConf with your own implementation.

In the body, you do the operation called "pattern matching":

``` scala
case ScallopException(message) =>
```

First, you check if "e" is "ScallopException", and if it is, you print the error message (conveniently provided to you via that pattern matching), print help, and then exit.

If that "e" is not a ScallopException, but some another error, it is "catched" by 

``` scala
case ex =>
```

which, in this case, serves as a "default" case in switch statement. Then you call the default implementation of onError with the same exception value (`super.onError(ex)`).

Hope that explains things a bit :)

**Comment by Rogach** [comment]
If you are new to Scala, I recommend book "Programming in Scala" by Martin Odersky. It is free and available online, and explains all these tricks very clearly and in great detail.

**Comment by 3goats** [comment]
Thanks for the detailed description. I'll order a copy of the book today.
