### ISSUE TITLE
Provide override option for `println` and `sys.exit`

### ISSUE THREAD

**Issue by hcannoodt** [scallop/scallop#240]
While the `sys.exit` is wrapped in an abstraction class `Compat` already, it would be great if we could override the actual implementation.
Additionally, the println could be wrapped too.

One possible implementation could be to set the `exit` to throw a custom `ExitException`.
Having the println wrapped and overridable would allow us to use our own logger methods to print messages in a standardized way.

Configuring the `throwError` option in Scallop doesn't provide a complete solution. Sure it doesn't call the `exit` method anymore (in some or all scenarios) but also doesn't provide any information about the expected output and instead only throws an exception.
E.g. `--help` would throw a `Help` exception but since the internal `builder` object is missing, there is no way for printing the help message afterwards.
Additionally, it would require the higher layers to have knowledge of Scallop exceptions and structures to print the required messages & call exit methods.

**Comment by Rogach** [comment]
I've added `stdoutPrintln`, `stderrPrintln` and `exitHandler` variables in `ScallopConf` - should handle all use-cases.

> E.g. --help would throw a Help exception but since the internal builder object is missing, there is no way for printing the help message afterwards.

`ScallopConf` actually has `printHelp` method, so you could print the help message through it (it's calling the same builder.printHelp method). But version string wasn't accessible that way. I've added `getFullHelpString`, `getVersionString` methods to mitigate such problems.

**Comment by hcannoodt** [comment]
Thanks! Took it into service already (well, on our develop branch anyway :) )
