### ISSUE TITLE
Scala Native 0.5

### ISSUE THREAD

**Issue by mio-19** [scallop/scallop#245]

**Comment by Rogach** [comment]
I tried building Scallop with Scala Native 0.5, but the build fails due to inability to resolve dependencies:

```
sbt.librarymanagement.ResolveException: Error downloading org.scala-native:scalalib_native0.5_2.13:2.13.6+0.5.1
```

I'm don't know much about Scala Native, maybe somebody more knowledgeable in it can help out here.
