### ISSUE TITLE
Feature request: declare default subcommand

### ISSUE THREAD

**Issue by Flowdalic** [scallop/scallop#248]
It would be great if scallop would support the declaration of a default subcommand. For example, consider a program `foo`, with two subcommands `send` and `check`:

```bash
$ foo send frank "Hi, how are you?"
Message send to frank
$ foo check
Connection is online
```

Then it would be great if `send` could be declared as default subcommand, so that

```bash
$ foo frank "Please also buy some eggs"
```

also works.

**Comment by Rogach** [comment]
No, sorry, this feels very confusing, and is likely to cause ambiguities.

**Comment by Flowdalic** [comment]
> No, sorry, this feels very confusing, and is likely to cause ambiguities.

No worries, and thanks for the response anyways. :)
