### ISSUE TITLE
ScallopConf.opt argument "argName" should be "arg"

### ISSUE THREAD

**Issue by larvanitis** [scallop/scallop#27]
In `ScallopConf.scala` the constructor param `argName` should be just `arg` according to the documentation on wiki and scaladoc.

```
def opt[A](
  ...
  argName: String = "arg",
  ...
```

**Comment by Rogach** [comment]
Thanks for the catch! Actually, in [scaladoc](http://rogach.github.com/scallop/#org.rogach.scallop.ScallopConf) it is still `argName` (it's `arg` for Scallop, not ScallopConf), but I forgot to change that in the wiki. Fixed that now (also renamed `arg` to `argName` in Scallop, for consistency).

**Comment by larvanitis** [comment]
First of all thank you for your time and project.
In my report I said _constructor param_ but that should be _method param_. Sorry it was late:P

Now when I said scaladoc I meant the actual comments in the source file as can be seen here:
https://github.com/Rogach/scallop/blob/master/src/main/scala/org.rogach.scallop/ScallopConf.scala#L84
which also has minor spelling mistake _ortion -> option._

Again thanks for everything. Really usefull lib.

**Comment by Rogach** [comment]
Ah, I misunderstood you. Now fixed that, too.

Thanks for reporting the bugs!
