### ISSUE TITLE
Build depende on nonexistent sbt plugin

### ISSUE THREAD

**Issue by runarorama** [scallop/scallop#28]
The build requires a github download

lazy val fmppPlugin = uri("git://github.com/aloiscochard/xsbt-fmpp-plugin.git")

which doesn't exist (404).

**Comment by Rogach** [comment]
That's not good. Seems that @aloiscochard deleted it for some reason. I'll try to ask him why that happened, and in the meanwhile I'll just add my cached version of fmpp-plugin to this project.

Thanks for catching this!

**Comment by Rogach** [comment]
I also updated `for-2.10` branch, so it would now build too.

**Comment by aloiscochard** [comment]
@Rogach hi mate, I moved the repo to the sbt organisation and renamed it: https://github.com/sbt/sbt-fmpp

BTW, I would recommend to depend on binary release instead of the git repo.

I'll merge some fix today and release/publish new version compatible with sbt 0.12

Sorry for all the problem this move created guys :-(

**Comment by Rogach** [comment]
@aloiscochard Thanks! That git dependency was an old artifact from the times when there was no binary release for sbt 0.12. I'll revert to binary dependency when the fix would hit maven repos.

**Comment by aloiscochard** [comment]
@Rogach I finally move it to sbt-community repo (so no need of adding resolvers for it), the new version 0.3 is here -> http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.github.sbt/sbt-fmpp/ 

You can simply add:
addSbtPlugin("com.github.sbt" %% "sbt-fmpp" % "0.3")

Let me know if you run into any issue :)

Ref: https://github.com/sbt/sbt-fmpp
