### ISSUE TITLE
Can't find 0.6.3

### ISSUE THREAD

**Issue by schauder** [scallop/scallop#29]
It's probably more an issue with me, than with your library, but I can't find version 0.6.3 mentioned in the  readme.md on any maven repository. The latest I can find seems to be 0.6.2. Can you provide a link to the repository, where it is hosted?

**Comment by Rogach** [comment]
Thanks for catching this!

Seems there was some trouble with releasing it to Sonatype's repo. I re-did the release, it is now available at https://oss.sonatype.org/content/repositories/releases/ (if you are using `sbt`, it would be used automatically), and the release would be available from Maven Central in 1-2 hours.

**Comment by schauder** [comment]
Wow, that was fast. Thank you
