### ISSUE TITLE
Typed Properties

### ISSUE THREAD

**Issue by alexy** [scallop/scallop#3]
Would it make sense to allow properties to be typed?  The same gist from my previous issue you've seen before contains a triple of numbers which determine certain behavior of my program.  I need three integers from those properties to have to do .toInt.  Not bad, but different from other options...  Should they be typable or properties are inherently strings?

**Comment by Rogach** [comment]
The typed properties now work - check out v0.3.3 :)

``` scala
object Conf extends ScallopConf(List("-Dkey1=1") {
  val properties = props[Int]('D')
}
Conf.properties("key1") // Some(1)
```
