### ISSUE TITLE
ScallopConf#errorMessageHandler has type String => Nothing rather than String => Unit

### ISSUE THREAD

**Issue by ghost** [scallop/scallop#33]
Due to a lack of type annotation. This means you can't override the handler to do anything except sys.exit or sys.error without terrible hackery, thereby preventing you from showing all the known errors at a single time.

**Comment by Rogach** [comment]
Thanks for reporting this bug!

You're right, I'll fix that annotation immediately.

About showing all the known errors - the library is fail-fast, thus errorMessageHandler is called only once anyway.
I don't think that it possible to collect all the errors - for example, if somebody mistyped the name of option, which takes a list of arguments, parser would be totally confused about what to do with the remainder of sequence.

**Comment by ghost** [comment]
no problem! understandable about the multiple errors; I was thinking about failed validation cases like required options but that doesn't mesh with the failed parse case.

closing since that change looks good to me.
