### ISSUE TITLE
trailArg[String] doesn't work with another subcommand name as argument

### ISSUE THREAD

**Issue by ghost** [scallop/scallop#34]
e.g. if you have

``` scala
        val help = new Subcommand("help") with Invoker with Described {
            val invoke = frontend.help _
            def description = "Show help about all commands or a specific command"
            val command = trailArg[String]("command", required=false, descr="Give help for the given command")
        }
```

And then a command line:

```
help show-events
```

`command` (presumably) receives `show` and then a parse error is generated:

```
> help show-events
Invalid command: Failed to parse the trailing argument list: 'help'
```

however input without a hyphen works correctly:

```
> help help
Show help about all commands or a specific command


 trailing arguments:
  command (not required)   Give help for the given command 
```

By the way, great library. Helped me out quite a bit, thanks!

**Comment by Rogach** [comment]
Thanks for reporting this!

I failed to reproduce this, though. I tried the following snippet:

``` scala
object Conf extends ScallopConf(Seq("help", "show-events")) { 
  val help = new Subcommand("help") { 
    val c = trailArg[String]("c", required = false) 
  } 
}
Conf.help.c
```

Can you share a bit more code? Seems something is missing in my example.

**Comment by Rogach** [comment]
I still can't reproduce the bug, but one observation - `Invalid command` message is tuned to print the whole unparsed argument line up to the end. What confuses me, is that only "help" is printed. Maybe "show-events" somehow got lost on it's way to conf object?

**Comment by ghost** [comment]
Interesting! I can't reproduce it with simple minimal case like yours either but it's definitely reproducible with my full application so I'll try and minimize that and see where it breaks.

**Comment by ghost** [comment]
Okay, minimized it. It seems to be triggered by empty subcommand in the same ScallopConf, maybe only before the command that shows the problem:

``` scala
import org.rogach.scallop.{Formatter, ScallopConf, Subcommand, stringConverter}

trait Options extends ScallopConf {
    /*
    val showTargets = new Subcommand("show-targets") {}
    */

    val help = new Subcommand("help")  {
        val command = trailArg[String]("command", required=false, descr="Give help for the given command")
    }

    errorMessageHandler = { message => sys.error(message) }
}

def test(args: String*): Option[String] = {
    val c = new ScallopConf(args) with Options
    c.verify()
    c.help.command.get
}

assert(test("help") == None)
assert(test("help", "show-targets") == Some("show-targets"))
```

This code works, but if you uncomment showTargets it breaks.

**Comment by ghost** [comment]
oh as a note, this example is actually somewhat _more_ broken than my actual app, in that this one won't even accept "help" by itself, which my real app does. Maybe that indicates that the cause has changed by my minimization, but this seems pretty close.

**Comment by Rogach** [comment]
Yes, now I reproduced it.

**Comment by Rogach** [comment]
I identified the bug, the fix is on the way :) 10-15 minutes, and I will publish a snapshot for you to test.

**Comment by ghost** [comment]
awesomely great turnaround time, batman!

**Comment by ghost** [comment]
ah! apparently I totally mischaracterized it, partly because the bug also depends on the order you define your subcommands - subcommands defined after help work fine because `subcommands.find` stops at the first match, e.g. `help`. 

it just so happened that all commands defined before `help` with only one or two exceptions I didn't try had hyphens in them.

**Comment by Rogach** [comment]
I'm working on publishing the snapshot, but sonatype doesn't accept it for some reason :(

**Comment by ghost** [comment]
Sonatype OSS seems unhealthy right now, I get a connection error trying to look.

**Comment by Rogach** [comment]
Here you go. If you are using sbt:

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += Seq("org.rogach" %% "scallop" % "0.6.5~1~SNAPSHOT")     
```

**Comment by ghost** [comment]
success! this fixed it in my full fledged application. thanks again
