### ISSUE TITLE
Option for customization for subcommand help

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#36]
It would be nice if --help were a little more customizable with how subcommands are displayed. For example, if you have 10 subcommands, the --help output is going to be huge and not very useful. Ideally (for me at least), --help would only show the options for a single subcommand. And --help without a subcommand would just list the subcommands and a short description. It would be nice if there were an option for something like this:

```
$ foo --help
Main Banner
 -f, --foo     foo option
 -b, --bar     bar option

Subcommands:
 baz     short description for baz command
 qaz     short description for qaz command

$ foo baz --help
Baz Subcommand Banner
 -h, --hello    hello option, specific to baz subcommand
 -w, --world    world option, specific to baz subcommand

$ foo qaz --help
Qaz Subcommand Banner
 -g, --goodbye      goodbye option, specific to baz subcommand
 -p, --planet       planet option, specific to baz subcommand
```

**Comment by Rogach** [comment]
Yes, that looks great!

I'll try to do it.

**Comment by Rogach** [comment]
Implemented. You can turn on new format for subcommands like in this snippet:

``` scala
new ScallopConf(Seq()) {
  shortSubcommandsHelp()
  // rest of definition
}
```

I published a snapshot, if you are using sbt, here's the incantation:

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.6.5~4~SNAPSHOT"
```

I think that @rmellgren would also be interested.

**Comment by ghost** [comment]
I sure would! My application has 22 subcommands ;-)

**Comment by ghost** [comment]
this works well for me, though I had to override onError to suppress sys.exit calls
