### ISSUE TITLE
ambiguity with opt[List[String]] and optional trailArg[String]

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#37]
Assume we have this:

```
object Conf extends ScallopConf(Seq("--option", "foo", "bar")) {
  val option = opt[List[String]]("option")
  val trail = trailArg[String]("trail", required=false)
}
```

Because `option` is a list, and `trail` is optional, the result is

```
option == Some(List(foo,bar))
trail == None
```

Although this makes sense, it is undesirable behavior for my use case. The reason being that the common case for me is that `--option` will be a list of one, and trail will be specified, i.e.

```
option == Some(List(foo))
trail == Some(bar)
```

One way to solve this ambiguity is to require the use of --, e.g. `--option foo -- bar`, but because that is the common case, it's undesirable to always require --.

Another solution, which would solve my problem, is to require the `--option` flag to be specified multiple times if more than one are needed, e.g. `--option foo --option bar --option baz`. So essentially a configuration option to make `--option foo bar baz` view `bar baz` as trailing arguments, rather than part of the `--option` list.

Curious what others think of this...

**Comment by Rogach** [comment]
I could reverse the trailing argument parser, but that would lead to even stranger things. Consider the following argument string: `--option foo`. Currently, `foo` is attributed to option. With reversed option parser, it would be attributed to trailing args - which will definitely be _very_ confusing.

As for your last solution - you can define custom [ValueConverter](http://rogach.github.com/scallop/#org.rogach.scallop.ValueConverter), that would do just that. (basically, you can just copy the code for the standard list converter, and change the argument type to ArgType.SINGLE):

``` scala
new ValueConverter[List[A]] {
  def parse(s:List[(String, List[String])]) = {
    try {
      val l = s.map(_._2).flatten.map(i => conv(i))
      if (l.isEmpty) Right(Some(Nil))
      else Right(Some(l))
    } catch { case _ =>
      Left(Unit)
    }
  }
  val manifest = m
  val argType = ArgType.SINGLE
}
```

**Comment by stevedlawrence** [comment]
Ah, I had not thought of that. This solved my problem perfectly. Thanks!

**Comment by stevedlawrence** [comment]
After using this method for a while, I've come across a bug that I can't seem to get around.

The goal was to make it so that you cannot use `-o foo bar baz`, but instead must use `-o foo -o bar -o baz`. The above solution works, but there still seems to be an issue with trailing args and args after the trailings args. For example, I have have this:

``` scala
object Conf extends scallop.ScallopConf(Seq("--option", "foo", "bar", "--option2", "baz")) {
  def singleListArgConverter[A](conv: String => A)(implicit m: Manifest[List[A]]) = new scallop.ValueConverter[List[A]] {
    def parse(s:List[(String, List[String])]) = { 
      try {
        s.map(println)
        val l = s.map(_._2).flatten.map(i => conv(i))
        if (l.isEmpty) Right(Some(Nil))
          else Right(Some(l))
      } catch {
          case _ => Left(Unit)
      }   
    }
    val manifest = m 
    val argType = scallop.ArgType.SINGLE
  }   

  val option = opt[List[String]]("option")(singleListArgConverter[String](a => a))
  val option2 = opt[String]("option2")
  val trail = trailArg[String]("trail", required=false)
} 
```

The results are:

``` scala
option == Some(List(foo,bar))
option2 == Some(baz)
trail == None
```

This is unexpected, as I thought I specified that `--option` could only allowing a single argument. Ideally, scallop would realize that there is a trailing arg in the middle, and I'd get the following:

``` scala
option == Some(List(foo))
option2 == Some(baz)
trail == Some(bar)
```

but I understand that that kindof breaks the meaning of a "trailing arg". Alternatively, it would be okay if scallop just threw an error saying there are options after a trailing arg. Thoughts? Is there anyway I can accomplish this?

Note that I tested this with both v0.8.0 and v0.8.1.

**Comment by Rogach** [comment]
Yes, it seems that Scallop.parse doesn't take into account ArgType on the option. You'll need to return Left(Unit) from ValueConverter.parse to indicate error, for example:

``` scala
def parse(s:List[(String, List[String])]) = { 
  try {
    s.foreach(println)
    assert(s.forall(_._2.size == 1))
    val l = s.map(_._2).flatten.map(i => conv(i))
    if (l.isEmpty) Right(Some(Nil))
      else Right(Some(l))
  } catch {
      case _ => Left(Unit)
  }   
}
```

This should result in message like this:

```
Wrong format for option 'option': 'foo bar'
```

**Comment by stevedlawrence** [comment]
Great! Seems to work. There error is a little confusing, since in my use case an option can never take a space separated list. But it seems this is the standard error whenever options are after the trailing arg, and I maybe be able to massage it into something more useful. Thanks!

**Comment by Rogach** [comment]
You're welcome :)

**Comment by Rogach** [comment]
About the original problem - I found several new aspects to this problem (for example, #51). So I decided to improve the behavior a little bit (will probably release it in `0.9.0`). Now, if trailing list option is not marked with `required = false` (default for trailing args is `true`), it consumes _at least_ one argument. So:

``` scala
val conf = new ScallopConf(Seq("--option", "foo", "bar")) {
  val option = opt[List[String]]()
  val trail = trailArg[List[String]]()
}
conf.option() ==== List("foo")
conf.trail() ==== List("bar")
```

To me, it makes a bit more sense. What do you think?

**Comment by stevedlawrence** [comment]
Yeah, makes sense to me.
