### ISSUE TITLE
sbt can't find 0.8.0 for scala 2.10.0

### ISSUE THREAD

**Issue by lrhazi** [scallop/scallop#41]
It looks like the repo has 2.10, not 2.10.0 ?

http://repo1.maven.org/maven2/org/rogach/scallop_2.10/0.8.0/

sbt error:

[info] Resolving org.rogach#scallop_2.10.0;0.8.0 ...
...
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/rogach/scallop_2.10.0/0.8.0/scallop_2.10.0-0.8.0.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.rogach#scallop_2.10.0;0.8.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/C:/Users/ll/workspace/demo/}default-f7ac75/*:update: sbt.ResolveException: unresolved dependency: org.rogach#scallop_2.10.0;0.8.0: not fo
und

**Comment by Rogach** [comment]
That's because of the new binary compatibility policy in Scala 2.10 - now it's enough to build the library against the single version of scala, and it would work properly on all versions of scala.

How do you specify the dependency? If you define it like:

``` scala
"org.rogach" %% "scallop" % "0.8.0"
```

, then sbt should go searching for `scallop_2.10` (by default), not `scallop_2.10.0`. Maybe you changed the value of `scalaBinaryVersion` setting somewhere?

**Comment by lrhazi** [comment]
I am newbie.. but here is what I have:

```
import AssemblyKeys._ // put this at the top of the file

name := "demo"

version := "1.0"

scalaVersion in ThisBuild := "2.10.0"

libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-actors" % "2.10.0"
)

libraryDependencies += "org.rogach" %% "scallop" % "0.8.0"

assemblySettings
```

What do I need to change, you think? 

Thanks a lot.

**Comment by Rogach** [comment]
Try setting `scalaVersion` like this:

``` scala
scalaVersion := "2.10.0"
```

**Comment by lrhazi** [comment]
That didnt seem to change its behavior:

```
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/rogach/scallop_2.10.0/0.8.0/scallop_2.10.0-0.8.0.pom
```

I tried setting the scala version to 2.10, but then it failed find the scala version itself.

**Comment by Rogach** [comment]
What sbt version do you use? I use `0.12.2`.

I created minimal `build.sbt`:

``` scala
scalaVersion := "2.10.0"

libraryDependencies += "org.rogach" %% "scallop" % "0.8.0"
```

and ran `sbt update`, had no errors.

**Comment by Rogach** [comment]
Maybe you have something in `project/` directory?

**Comment by lrhazi** [comment]
Nothing in the project dir, but I have this in the plugins dir, in my homedir:

```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.1.0")

resolvers += Resolver.url("artifactory", url("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.8.5")
```

**Comment by Rogach** [comment]
What do the following commands output for you? (on sbt prompt):

```
show scala-version
show scala-binary-version
show sbt-version
show sbt-binary-version
```

**Comment by lrhazi** [comment]
```
> show scala-version
[info] 2.10.0
> show scala-binary-version
[error] Not a valid project ID: scala-binary-version
[error] Not a valid configuration: scala-binary-version
[error] Not a valid key: scala-binary-version (similar: scala-version, cross-scala-versions, sbt-version)
[error] show scala-binary-version
> show sbt-version
[info] 0.11.3
> show sbt-
sbt-dependency   sbt-plugin       sbt-resolver     sbt-version
```

**Comment by Rogach** [comment]
You use sbt `0.11.3`. I seriously think that it would be better to upgrade to `0.12.x` sbt release, since it's tuned to work with scala `2.10`. If you can't upgrade, you can specify dependency to the library like this:

``` scala
"org.rogach" % "scallop_2.10" % "0.8.0"
```

And it should work. Note that you'll probably need to follow the same pattern for most of other libs.

**Comment by lrhazi** [comment]
```
"org.rogach" % "scallop_2.10" % "0.8.0"
```

that worked for me, thank you so much.

I tried upgrading sbt, but could not figure out how to :)

**Comment by Rogach** [comment]
How did you install sbt? Some package?

**Comment by lrhazi** [comment]
With the MSI for Windows. Simply redownloading the current MSI on the sbt site does not seem to upgrade it.

**Comment by Rogach** [comment]
Sorry, can't help with Windows :( You can try asking in sbt irc channel on freenode, or ask on mailing list. Good luck!
