### ISSUE TITLE
more visible link to uasage of scallop

### ISSUE THREAD

**Issue by xhudik** [scallop/scallop#44]
Hi, Rogach
first of all - thanks for your library. I'm just started to using it - it looks useful and userfriendly.

The only problem I had was to find out documentation how-to use the library (I'm talking about your wiki (https://github.com/Rogach/scallop/wiki). I was through your basic quick example and whole https://github.com/Rogach/scallop - but didn't find it. It seems I'm not the only one: http://stackoverflow.com/questions/13059909/scala-command-line-parser-using-scallop . I'd propose to move your sentence: "For more info, you can look into the project wiki or consult the API docs." right after "Scallop supports:" paragraph. Maybe also changing the sentence into: For more info, how-to usage you can look into the project wiki or consult the API docs."

cheers, Tomas

**Comment by Rogach** [comment]
Yes, that would definitely make things easier to understand. Thank you for the suggestion!

**Comment by Rogach** [comment]
Is it better now?

**Comment by xhudik** [comment]
yep, i think everyone interested in your project will go through list of supported features and if want to know more he will find the link immediately (without trying "Quick example" which is not the right thing for a novice)

thanks!!
