### ISSUE TITLE
ordering of help items

### ISSUE THREAD

**Issue by xhudik** [scallop/scallop#46]
Hi,
I was wondering whether it is possible to change order of arguments while printing out help message. It seems options/arguments are ordered by alphabet now. I think there can be situation when some other logical ordering would be better. E.g. 
...
Options:

```
  --help         Show this message 
  --in  <arg>    input corpus 
  --out  <arg>   output corpus (default = corpus_out)
```

...
But it would be better to have:
...
Options:

```
  --in  <arg>    input corpus 
  --out  <arg>   output corpus (default = corpus_out)
  --help         Show this message 
```

...

User would be given items ordering which is better readable and more suitable (having info on printing this help page in first place is not ok).

What about a new optional parameter? e.g:

```
  val sl = opt[String]("sl", noshort=true, descr = "set source language", required=true, help_order=1)
```

Disadvantage of this approach is that programmer would have to take care if arguments are subject of change, but I think it would worth the cost in many situations 

what do you think?
Thanks, Tomas

**Comment by Rogach** [comment]
With big number of arguments, doing all this by hand is going to become tedious and error-prone - not good. There's one thing that I did notice, though - a lot of CLI apps put all their options in alphabetical order, but `--help` and `--version` are placed at the end. Maybe this route will be better?

**Comment by xhudik** [comment]
yes, good point! Or, maybe add argument telling this option is not first-order citizen, put it down ( --help, --version and other some user specific option(s) )

**Comment by Rogach** [comment]
Looking at `tar` main page, I can see another pattern - some options are marked as "main" options, and are put into separate section near the top of the page. So I'll propose the following syntax:

``` scala
object Conf extends ScallopConf(args) {
  mainOptions = Seq(apples, bananas)
  val apples = opt[Int]()
  val bananas = opt[Int]()
  val coconuts = opt[Int]()
}
```

And the output:

```
test, v0.0.1

MAIN OPTIONS:
  --apples, -a  <arg>
  --bananas, -b  <arg>
OTHER OPTIONS:
  --coconuts, -c  <arg>
  --help
  --version
```

That and the `--help` and `--version` to the bottom of the page. What do you think?

**Comment by Rogach** [comment]
And in main options, you would have the ability to specify whatever option order you need (since the type is `Seq`).

**Comment by xhudik** [comment]
we came to similar solution :). I;m just thinking whether it is good idea to put there also description like "MAIN OPTIONS:" - another argument could be confusing, maybe just leaving a blank line ..

**Comment by Rogach** [comment]
Ok. So something like this:

```
test, v0.0.1

  --apples, -a  <arg>
  --bananas, -b  <arg>

  --coconuts, -c  <arg>
  --help
  --version
```

**Comment by xhudik** [comment]
yes - i think this could logically separate different classes of arguments. Maybe in future we will come to decision that it is not enough but for now I think is ok...

thanks very much!

**Comment by Rogach** [comment]
By the way, I'll probably hardcode the reference to `--help` and `--version`, so you wouldn't need to define them in your options definitions anymore.

**Comment by xhudik** [comment]
hard-coding those 2 options suits me well, but I think having a possibility to make some logical blocks (also from user specified options) would be useful (as you already  proposed:

```
test, v0.0.1

 --apples, -a  <arg>
 --bananas, -b  <arg>

 --coconuts, -c  <arg>
 --help
 --version
```

Of course, If it is difficult from programming point of you, let's stick to hard-coding ...

**Comment by Rogach** [comment]
Sorry, don't understand your last point - what logical block are you talking about? 

When I talked about hard-coding, I meant that all Scallop programs respond to `--help` and `--version` anyway, so they should appear in all help outputs (currently, they do not).

**Comment by xhudik** [comment]
sorry I probably didn't get your reply:
"By the way, I'll probably hardcode the reference to --help and --version, so you wouldn't need to define them in your options definitions anymore."

I understood it as you switch from our earlier discussion to "just" hard-code 2 options(--help, --version). But maybe you meant that you hard-code those two options but if a user wants some other option(--coconuts) can be added to them, i.e.:

```
  test, v0.0.1

--apples, -a  <arg>
--bananas, -b  <arg>

--coconuts, -c  <arg>
--help
--version
```

So, which of these 2 understanding is true? Or, you meant something else?:)

**Comment by Rogach** [comment]
I meant that now, there would be two groups of options: `main` and `other`, and `--help` with `--version` will be placed at the end of `other` section.

**Comment by xhudik** [comment]
ok -so 2nd understanding  -  yes, this is great!
thanks

**Comment by Rogach** [comment]
So, the feature is implemented, and I published a snapshot (for 2.9.x):

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.8.0~1~SNAPSHOT"
```

What do you think?

**Comment by xhudik** [comment]
yes, after inserting:  "mainOptions":

```
   ScallopConf(args, "mainOptions")
```

it was working,  version and help was at the bottom of help list. I was unable to add some of my own command down to the help, version - how this can be done?

**Comment by Rogach** [comment]
Sorry, I don't understand your snippet - it shouldn't even compile?

**Comment by Rogach** [comment]
Ah, I see now. The right syntax is like this:

``` scala
object Conf extends ScallopConf(args) {
  mainOptions = Seq(apples, bananas)
  val apples = opt[Int]()
  val bananas = opt[Int]()
  val coconuts = opt[Int]()
}
```

**Comment by xhudik** [comment]
aaa , yes it is working. I found a small problem if you provide your own line for help (e.g. you make sw for different language), 2 versions of help appear:

```
  --help         TRY: it's me!
  --help         Show help message
  --version      Show version of this program
```

line for my help:

```
  val help = opt[Boolean]("help", noshort = true, descr = "TRY: it's me!")
```

So I'm not sure now whether the hard-coding of help and version is a good idea. Maybe just mainOptions = Seq(apples, bananas, help) would be good enough...

**Comment by Rogach** [comment]
I'll then hard-code them by default, but if user provides his own version, then I'll leave his variant.

**Comment by xhudik** [comment]
sounds reasonable. Thanks for fast and reliable solving things!!!

**Comment by Rogach** [comment]
Implemented, published new snapshot:

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.8.0~2~SNAPSHOT"
```

**Comment by Rogach** [comment]
Ok, I hope you like the new feature :) I'm closing this issue, and will publish new version now (`0.8.1`) - it will sync to Maven Central in 1-2 hours.
