### ISSUE TITLE
not enough arguments for constructor ScallopConf

### ISSUE THREAD

**Issue by lrhazi** [scallop/scallop#48]
I moved my code from one machine to another, and now my eclipse/scala complain  that:

Description Resource    Path    Location    Type
not enough arguments for constructor ScallopConf: (args: Seq[String], commandname: String)org.rogach.scallop.ScallopConf    main.scala  /g2i2-ingest/src/main/scala/edu/georgetown/g2i2 line 26 Scala Problem

Probably some version issues, but could this error help someone guess what the problem is?

the error is the following line;

``` scala
class Conf(arguments: Seq[String]) extends ScallopConf(arguments) {

```

**Comment by Rogach** [comment]
What version of Scallop are you using?

Also, could you post the whole source file? I suspect some issue with the syntax (since ScallopConf should totally work in this case).

**Comment by lrhazi** [comment]
I just updated to the very latest, trying to solve the problem. from 0.8.0 to 0.8.1...

The code actually compiles and runs fine, I just realized. Only eclipse causes the issue.. I have a line that instantiates that Conf class like so:

val conf = new Conf(args)

and args comes from Scala : 

object Ingest extends App {

Somehow my previous eclipse installation handled this OK, and this current one does not like it... am sure it's an eclipse config/customization/run configuration or such... Thanks a lot.

**Comment by Rogach** [comment]
You're welcome :)

I don't use Eclipse, so can't offer much help on that - but when I ran into such problems, full rebuild (clean, build) or restart usually helped. Anyway, that's extremely strange - you should consider opening a bug in their bug tracker.
