### ISSUE TITLE
RFE: Add option groups

### ISSUE THREAD

**Issue by lrhazi** [scallop/scallop#49]
I wonder if it would be useful to add the possibility of defining groups of options such that some options are required in each group.. 

I had several arguments defined, with few being required args, then needed to add a new argument which if present  should make the previously required args not required anymore... I am thinking being able to say this new argument is part of a new group would make it easier.

Thanks a lot,
Mohamed.

**Comment by Rogach** [comment]
Could you give me an example - currently, I can't understand it clearly?

Is there any chance that [arguments validation](https://github.com/Rogach/scallop/wiki/Arguments-validation) already does that?

**Comment by lrhazi** [comment]
I have not seen that and probably would.. but here what I meant:

-a required
-b required
-c optional

Now I need to add  
-z required
-y optional

and I want to say, 
- if -z is present, don't require -a, and -b 
- if -a is present, don't require -z

**Comment by Rogach** [comment]
Well, the obvious approach would be to turn off the `required` attribute on all those options, and then do the validation by hand after parsing is done - using `ScallopOption.isSupplied` and reporting error if something is wrong (if you need some example code for that, I can write it).

That said, I'll think about it some more - maybe I'll create a good helper method to do it.

**Comment by lrhazi** [comment]
Cool, that's pretty much what am doing for now. Thanks a lot.
