### ISSUE TITLE
Support for list of boolean flags

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#50]
I would like to be able to support allowing the user to specify a flag multiple times, for example `-vvvv` to set a verbosity level of 4. After playing around for a bit, I found that I could sort of accomplish this through the use of List[Booleans] and counting how many there were. The code I added was:

``` scala
implicit val flagListConverter = new scallop.ValueConverter[List[Boolean]] {
  def parse(s: List[(String, List[String])]) = {
    try {
      val l = s.map(_ => true)
      Right(Some(l))
    } catch {
      case _ => Left(Unit)
    }
  }
  val manifest = implicitly[Manifest[List[Boolean]]]
  val argType = scallop.ArgType.FLAG
}
```

With this I can define an option like this:

``` scala
val verbose = opt[List[Boolean]]("verbose", ...)
```

and then determine the count with

``` scala
Conf.verbose().length
```

My question, is this the right way to do this? Perhaps this (or something similar) should be part of Scallop?

**Comment by Rogach** [comment]
Small improvement - so you won't need to call `.length` each time, and still keep the proper implicit converter resolution (also, note that you don't need to write "verbose" in method invocation, Scallop determines that from value name):

``` scala
val verbose = opt[List[Boolean]](...).map(_.length)
```

Yes, I'll think about adding something like this. The syntax could be like:

``` scala
val verbose = counted()
```

I don't like `counted`, though. Maybe you can suggest a better name?

**Comment by stevedlawrence** [comment]
Hmm, I'm not against counted(), but I agree that it's not the best name. Maybe tally()? Not sure that is much better, though. 

Honestly, the .map(_.length) solution isn't terrible. I don't think it would be the worst thing for this to just be a documented scallop convention for having this type of thing (though a built-in feature would make things a bit more user friendly).

**Comment by Rogach** [comment]
.map(_.length) requires the user to define `flagListConverter` anyway, and that requires some knowledge - not very good for first-time user.

I like `tally` a lot better than `counted` (except I had to look for the word in the dictionary, actually :) ). I think I'll implement it as `tally`.

I'll probably do it in 4 hours from now, and will publish a snapshot for testing.

**Comment by stevedlawrence** [comment]
Awesome! Thanks!

**Comment by Rogach** [comment]
I implemented it, and published a snapshot (for scala 2.10.x):

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.9.0~1~SNAPSHOT"
```

**Comment by stevedlawrence** [comment]
I noticed you pushed a ~2 snapshot. Tested with that and it works for me! Thanks!

**Comment by Rogach** [comment]
I'll publish `0.9.1` version now, then. If all goes well, it will be synced to Maven Central in 2 hours.
