### ISSUE TITLE
List option not maintaining order

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#59]
Note: This is tested with the 0.9.1~3~SNAPSHOT release.

Say we have two options 1) a list of strings 2) optional trailing arg, i.e.

``` scala
object Conf extends scallop.ScallopConf(args) {
  val l = opt[List[String]](descr = "list of strings")
  val t = trailArg[String](required = false, descr = "optional traling arg")
}   
```

With `args = List("-l", "1", "-l", "2")`, we get the correct output:

```
Conf.l == Some(List(1,2))
```

However, with `args = List("-l", "1", "-l", "2", "--", "trail")`, the order of the `-l` arguments are reversed:

```
Conf.t == Some("trail")
Conf.l == Some(List(2,1))
```

Similarly, if instead of the trailing arg, I just specify a normal option, like this:

```
object Conf extends scallop.ScallopConf(args) {
  val l = opt[List[String]](descr = "list of strings")
  val o = opt[String](descr = "string")
}   
```

Then specifying the `-o` option after the list causes the wrong order as well, i.e. `args = List("-l", "1", "-l", "2", "-o", "foo")` results in

```
Conf.o == Some("foo")
Conf.l == Some(List(2,1))
```

You get the correct order if `-o` is not specified.

It seems like the order of the list should always be in the order specified in the arguments, right?

**Comment by Rogach** [comment]
Yes, that's a sure bug. Will look into it now.

**Comment by Rogach** [comment]
I fixed that, and published a snapshot (for scala 2.10.x):

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.9.1~4~SNAPSHOT"
```

**Comment by stevedlawrence** [comment]
Looks good. Thanks again!

**Comment by Rogach** [comment]
You're welcome :) I'll probably cut a release with all the fixes in 1-2 days (I'm waiting for @ellchow to respond on #55).
