### ISSUE TITLE
validation ignored in subcommands

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#60]
When testing the Issue #55, i noticed that validation (both current validation and the new validateOpt function) don't work in subcommands. Should this work? It looks like the functions are never called. For example, i would expect this to fail validation:

``` scala
    object Conf extends ScallopConf(List("sub1", "-a", "1", "-b", "5")) {
      val sub1 = new scallop.Subcommand("sub1") {
        val apples = opt[Int](descr = "apples")
        val bananas = opt[Int](descr = "bananas") 

        validate(apples, bananas) { (a, b) =>
          if (a + b >= 3)
            Left("sub1: a + b must  be < 3")
          else
            Right(Unit)
        }
      }   

      val sub2 = new Subcommand("sub2") {
        val apples = opt[Int](descr = "apples")
        val bananas = opt[Int](descr = "bananas") 
        validate(apples, bananas) { (a, b) =>
          if (a + b < 3)
            Left("sub2: a + b must be >= 3")
          else
            Right(Unit)
        }   
      }   
    }  
```

I did find that I can move the validate functions out of the subcommands, giving something like this:

``` scala
validate(sub1.apples, sub1.bananas) { ... }

validate(sub2.apples, sub2.bananas) {... }
```

And it seems to work, which surprises me, since it's seems like it would try to validate a subcommand that didn't exist.

**Comment by Rogach** [comment]
Yes, that will run all the validations. I fixed the issue, now subcommand validations run properly, and only validations on selected command are being ran.

Snapshot (for scala 2.10.x):

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.9.1~7~SNAPSHOT"
```

Still, I have no way to forbid the user to refer to subcommands' options in parent validations. It won't be disastrous if somebody does it, just not very good.

**Comment by stevedlawrence** [comment]
Works for me. Thanks!
