### ISSUE TITLE
long option description - some characters (last in line) are being ommited

### ISSUE THREAD

**Issue by hochgi** [scallop/scallop#65]
i've noticed that when i'm providing a long string for `descr` my lines are being wrapped. well, some times, the last character is being ommited. an example:

`val nodeMachinesList = opt[String]("node.machines.list", noshort = true, descr = "names of the other hosts in this cluster, seperated by a colon ':'," +
                                       " you can also specify name generator list with the syntax: '... :prefix[from-to]suffix: ...', for example: " +
                                       "'cmw-p:cmw0[1-9]-p:cmw10-p' is equivalent to: " +
                                       "'cmw-p:cmw01-p:cmw02-p:cmw03-p:cmw04-p:cmw05-p:cmw06-p:cmw07-p:cmw08-p:cmw09-p:cmw10-p'")`

and for this i'm getting in the help:

`--node.machines.list  <arg>   names of the other hosts in this cluster,
                                    seperated by a colon ':', you can also specif
                                    name generator list with the syntax: '...
                                    :prefix[from-to]suffix: ...', for example:
                                    'cmw-p:cmw0[1-9]-p:cmw10-p' is equivalent to:
                                    'cmw-p:cmw01-p:cmw02-p:cmw03-p:cmw04-p:cmw05-p:cmw06-p:cmw07-p:cmw08-p:cmw09-p:cmw10-p'`

notice that the 'y' in "specify" is missing from the help printout.
it happened on some other long descriptions (i have quite a lot), but i can't post it publicly since it contains some sensitive information.

**Comment by Rogach** [comment]
Thank you for reporting this!
Other descriptions are not needed, I think - one reproducible sample is enough. I'll fix it and post a snapshot so you can test your other descriptions locally.

**Comment by Rogach** [comment]
I fixed it, and published a snapshot (for scala 2.10.x):

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.9.2~3~SNAPSHOT"
```

**Comment by hochgi** [comment]
thanks! BTW, my code is compiled against scala 2.9.1
i would realy appreciate a snapshot suitable for it.

thanks again!

**Comment by Rogach** [comment]
Sure, no problem. Here's the snapshot for 2.9.x:

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.9.2~4~SNAPSHOT"
```

**Comment by hochgi** [comment]
thanks! the help printout is fixed!
