### ISSUE TITLE
more arguments to validate & validateOpt

### ISSUE THREAD

**Issue by hochgi** [scallop/scallop#66]
currently, it is possible only up to 7 arguments.
in my current usage, i have over 20 different options.
i'm getting a comp error, when writing a validateOpt for all of the arguments
(just making sure user doesn't invoke unrelated tasks together, i got several command groups, and i don't want to allow mixing a combination from different groups...)

can you enhance the number of arguments?
(i saw you're using a macro: ScallopConfValidations.fm, so i guess it's just changing the number 7)

how many would be enough?
i don't know exactly, i currently have 20 options, with a few more planned i still haven't written.
i guess 25 or 30 should be enough for my use case.

thank you!

**Comment by Rogach** [comment]
Sure, I'll try to make more possible arguments. There's one small problem - possible huge increase in bytecode size, if I make too many overloaded methods (I saw similar problem when increasing tuple size in scala library).

Also, you may be interested in [#64](https://github.com/Rogach/scallop/issues/64#issuecomment-18323209) - maybe you can make your dependencies definitions a bit more granular, and the code will be easier to read?

**Comment by hochgi** [comment]
this does not exactly works for my usage. i have a few "command groups", consider:
`--aFoo, --aBar, --bFoo, --bBar, --cFoo, --cBar`
and i want to allow combinations from only a's or only b's or only c's.
if i could have something like `validateIntersectionIsEmpty(Set(aFoo,aBar),Set(bFoo,bBar))`
with error message indicating you can't supply both `aFoo` & `bBar` (for example), that would work best for me.

**Comment by Rogach** [comment]
Subcommands also don't help with that?

Anyway, that function is quite easy to create:

``` scala
// haven't compiled this, but something along those lines should work
def validateIntersectionIsEmpty(optSets: List[Set[ScallopOption[_]]]) = {
  validations :+= new Function0[Either[String, Unit]] {
    def apply = {
      optSets.map { set =>
        set.find(_.isSupplied).flatMap { opt1 =>
          optSets.filter(set!=).find(_.exists(_.isSupplied)).map { conflictSet =>
            val opt2 = conflictSet.find(_.isSupplied).get
            Some("your error message")
          }
        }
      }.flatten.headOption.fold(Right(Unit))(Left)
    }
  }
}

```

**Comment by Rogach** [comment]
So, I compiled and published a snapshot with `validate` and `validateOpt` working with up to 22 arguments. I can't go further - because scala distribution only provides FunctionN types up to Function22 (if you _really_ want to get more, [here's how](http://rogach-scala.blogspot.ru/2013_02_01_archive.html)).

Here's snapshot for scala 2.10.x:

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.9.2~4~SNAPSHOT"
```

And here's for scala 2.9.x:

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.9.2~5~SNAPSHOT"
```

Increase in binary size is not _that_ bad - 67 kb (from 503 to 570), but still, your approach doesn't scale - there will be almost no sane way to work with it after 22 options. Did my attempt on `validateIntersectionIsEmpty` help?

**Comment by Rogach** [comment]
If you still need this, please let me know.

**Comment by hochgi** [comment]
sorry for the delay. at the end I resulted with a solution similar to yours:

``` scala
    def validateIntersectionIsEmpty(scallopSets: List[Set[org.rogach.scallop.ScallopOption[_]]]) = {
        validations :+= new Function0[Either[String, Unit]] {
            def apply = {
                (scallopSets map (s => Some(s.exists(_.isSupplied))) foldLeft (Some(false): Option[Boolean])) {
                        case (Some(a), Some(b)) => {
                            if(a && b) None
                            else if(a || b) Some(true)
                            else /*if(!a && !b)*/ Some(false)
                        }
                        case (_, _) => None
                } match {
                    case None => Left("seems like you're trying to execute some unrelated actions all at once. well... don't.")
                    case Some(_) => Right(Unit)
                }
            }
        }
    }
```

thank you very much for the great work on Scallop!
I just love using it!
