### ISSUE TITLE
read options from a config file

### ISSUE THREAD

**Issue by alexy** [scallop/scallop#7]
place all options into a config file to read them back as a canned config! 

--config my.scallop

**Comment by Rogach** [comment]
I plan to implement like following - if the first item of the argument list is of the form "@file-name", then arguments are read from it (splitting at space characters and newlines) and only from it. All arguments after it are ignored.

**Comment by Rogach** [comment]
Implemented in `master`.

Also, I added reading options from stdin:

```
someprogram @--
```
