### ISSUE TITLE
Allow for optional unnamed integer options

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#71]
Some commands have integer options that do not require the option name, for example:

``` bash
git log -3  # show the last three commits
tail -5 /var/log/messages # show the last five lines in /var/log/messages
```

It would be nice if this were doable in scallop. It should still allow the short/long names, so the usage would look something like this:

``` bash
-<number>, -f <number>, --foo <number>
```

Of course there would be some restrictions, like it only works for positive integer values (perhaps any numeric value should be allowed? and maybe --3 could allow negative values?), and only one option can have this capability to prevent ambiguities.

**Comment by Rogach** [comment]
Am I right in assuming that those integer options are always trailing options?

**Comment by stevedlawrence** [comment]
Nope, they do not have to be trailing options. For example, these are perfectly legal for the git example:

``` bash
git log -3 -p
git log -20 path/to/file.scala
```

In this case, -p is allowed to come after the -3 option, and the filename (which is a trailing arg) comes after the -20 option. The above commands are equivalent to

``` bash
git log -n 3 -p
git log --max-count 20 path/to/file.scala
```

(-n is the short name for --max-count)

**Comment by Rogach** [comment]
I'll think about it :) I'm quite short on time now, so I can't implement it right away, but I'll try.

One of the biggest questions is the syntax for this option type and enforcement that there is only one such option (otherwise there will be ambiguity).

**Comment by Rogach** [comment]
By the way, maybe it will be easier for you to do this in pre-processing step? For example:

``` scala
val args = getArgsFromSomewhere // "--tree palm -3"
val fixedArgs = preprocessArgs(args) // => "--tree palm --count 3"
val opts = Options(fixedArgs) // pass to scallop
```

**Comment by stevedlawrence** [comment]
That might be a good temporary solution. But I find preprocessing tends to be a pain. Especially when things get complex like if there are nested subcommands or something.

However, I'm actually trying my hand at adding this feature (more of an RFC type of patch, though). I have the basics working, but there are still a few edge cases to be ironed out (e.g. negative numbers and lists of numbers cause problems).

Like you, I don't have a whole lot of free time, so it might be a couple of weeks until I get something that's reviewable.

The way I have it right now is you just add "numNoName=true" (I'm not a fan of that parameter name, but that's an easy change) to the option where you want this available, and scallop does everything from there. That's the idea anyway, so it might looks something like this:

``` scala
object Conf extends ScallopConf(List("-a", "3", "-4", "--coconuts", "5")) {
  val apples = opt[Int]("apples")
  val bananas = opt[Int]("bananas", numNoName=true)
  val coconuts = opt[Int]("coconuts")
  verify
}   
Conf.apples() should equal (3) 
Conf.bananas() should equal (4) 
Conf.coconuts() should equal (5) 
```

**Comment by Rogach** [comment]
Well, I don't like adding case-specific flags to `opt` method, but currently that seems to be the best solution. Ping me when you'll have something reviewable - maybe I'll find a way to abstract that in more-or-less clean way.

By the way, what would happen if there are two options with `numNoName = true`?

**Comment by stevedlawrence** [comment]
In the verify function, I just count the number of opts that have `numNoName == true`. If there's more than one, then an exception is thrown.
