### ISSUE TITLE
do not generate negative toggle option if prefix is null

### ISSUE THREAD

**Issue by hsn10** [scallop/scallop#74]
-h, --help            print help
      --nullhelp

**Comment by Rogach** [comment]
Why can't you simply create non-toggle boolean option?

**Comment by hsn10** [comment]
i could, but should not it throw illegalargumentexception if it is not designed to be used that way?

**Comment by Rogach** [comment]
Well, in general, in scala you don't pass nulls around :) So if something doesn't accept `scala.Option`, it is assumed that it accepts normal, non-null value (unless documentation explicitly specifies otherwise).

You are proposing addition of null check in the whole library?

**Comment by hsn10** [comment]
no, but with slight code change it could throw NPE.

**Comment by Rogach** [comment]
Yes, that's exactly why in idiomatic scala we don't pass nulls in the code - because slight code changes will result in NPEs all over the place. I'd even say that in most cases, passing `null` into some method invokes something like "undefined behavior" - it may work, or it may fail.

**Comment by Rogach** [comment]
I'll close the issue now. If you have something to add to this issue, please reopen it!
