### ISSUE TITLE
Basic usage example gives warning when compiled with -Xlint

### ISSUE THREAD

**Issue by djneades** [scallop/scallop#78]
First, thank you for Scallop – it’s proved very useful to us.

Compiling the basic usage example (https://github.com/scallop/scallop/wiki/Basic-usage) with the -Xlint option gives the warning:

"Selecting value apples from class Conf, which extends scala.DelayedInit, is likely to yield an uninitialized value"

Now, I am guessing that this is benign (although I confess I haven’t invested the time into understanding why ScallopConf needs to extend DelayedInit), but it’s a really scary warning, particularly for those relatively new to Scala. Our application (which has relatively straightforward argument parsing needs) generates 15 separate such warnings, which is a lot of noise in a build that is otherwise clean as far as -Xlint is concerned.

It would therefore be great if Scallop could be adjusted not to be noisy with respect to -Xlint.

Many thanks in advance for your attention.

**Comment by clhodapp** [comment]
This is a problem. I want to solve it. It may take a while, but I'll definitely do it!

**Comment by djneades** [comment]
Hi Christopher,

Thank you! I really do appreciate all your work on Scallop, and for your making the fruits of your labour available for free to the community.

**Comment by pommedeterresautee** [comment]
Another noise is when using something like:

``` scala
  validateOpt(inputFile) {
    case Some(path) ⇒ Right(Unit)
    case None       ⇒ Left("Provide an input file!")
  }
```

It raises.

```
[warn] PATH....\CommandLineParser.scala:79: discarded non-Unit value
[warn]     case Some(path) ? Right(Unit)
```

**Comment by mslinn** [comment]
Here is a simple [solution](http://stackoverflow.com/questions/21331929/scalas-delayedinit-and-scallop/24457632?noredirect=1)

**Comment by Rogach** [comment]
Since DelayedInit seems to be leaving us soon, I'm thinking about removing that hack with .afterInit(). I probably will require manual .verify() call after options initialization.

That will even bring some benefits - it will be easy to understand when the parsing/verification process takes place, and from where you can expect errors to happen.
