### ISSUE TITLE
any way to use mixin with scallop

### ISSUE THREAD

**Issue by heligan** [scallop/scallop#79]
Let's say I have several common options, with some application-specific options
class CommonOptions (args: Seq[String]) extend ScallopConf (args) {
  val abc = opt ...
}

trait InputOption { self: ScallopConf =>
  val input = opt ...
}

trait OutputOption { self: ScallopConf =>
  val input = opt ...
}

class FooOptions (args: Seq[String]) extends CommonOptions (args) with InputOption
class BarOptions (args: Seq[String]) extends CommonOptions (args) with InputOption with OutputOption

This idea doesn't work with scallop. It seems that CommonOptions (args) are called before InputOption is initialized and then it throws an exception saying
It seems you tried to get option value before you constructed all options (maybe you forgot to call .verify method?). Please, move all extraction of values to after 'verify' method in ScallopConf.

Is there a way to get the mixin working with Scallop?

**Comment by b-studios** [comment]
I ran into the exact same problem. Since it is still not fixed I came up with the following workaround: Calling `afterInit` manually triggers the necessary call to `verify`. That solved the problem for me.

``` scala
class FooOptions (args: Seq[String]) extends CommonOptions (args) with InputOption { afterInit }
```

**Comment by Rogach** [comment]
I'll be removing `afterInit` hack in next release (DelayedInit is deprecated anyway), so next version will require `verify` call before usage anyway, so this problem should go away.
