### ISSUE TITLE
Publish against scala 2.11 milestones

### ISSUE THREAD

**Issue by inkytonik** [scallop/scallop#83]
As the Scala 2.11 release process is nearing an end, it would be useful to have published versions of Scallop for the M7 and M8 milestones. This will help users of the library test their code against these milestones before RC stage hits. Thanks.

**Comment by inkytonik** [comment]
Actually, after more reflection, I think publishing against M8 would be enough for me. My code has some non-trivial problems with M7 due to compiler bugs that are fixed in M8.

**Comment by clhodapp** [comment]
0.9.5 is published against 2.11.0-M8. It should sync to Maven Central within a few hours.

**Comment by inkytonik** [comment]
Many thanks. It's working fine for me.
