### ISSUE TITLE
Publish against scala 2.11.0-RC3

### ISSUE THREAD

**Issue by inkytonik** [scallop/scallop#84]
Any chance of publishing Scallop against Scala 2.11.0-RC3? This version looks likely to be the last before 2.11.0 final but I have a bug I may need to report before then if it's real. I'd like to rule out binary incompatibility with the M8 version of Scallop which is currently the latest. Thanks.

**Comment by clhodapp** [comment]
Sorry I somehow missed this request (I've been on vacation since about the time you made it, and just got back last night). I'm pretty busy at the moment. I'll try to do it tomorrow evening.

**Comment by inkytonik** [comment]
Thanks. Much appreciated. I believe an RC4 will be necessary but it shouldn't be much different to RC3.

**Comment by hrj** [comment]
Any updates on this? I would like to test my project with scala 2.11.0-RC3, but scallop is the only dependency holding me back (speaking as a lazy developer who wants to avoid building scallop locally).

**Comment by clhodapp** [comment]
I'll likely be building it in something like 8 hours or so.

**Comment by clhodapp** [comment]
I've published a build against 2.11.0-RC3. It should sync to Maven Central shortly.

**Comment by inkytonik** [comment]
Many thanks!
