### ISSUE TITLE
ValueConverter parse method called multiple times

### ISSUE THREAD

**Issue by borice** [scallop/scallop#86]
I'm wondering whether this is expected behavior. I've defined a custom ValueConverter to convert a string from the command line to a particular custom type my application uses.  The cmd line only has one such argument that needs to be converted, however I see that the "parse" method of my custom ValueConverter is being called multiple times.

Is this normal?
Using scallop 0.9.5

Thank you,
Boris

**Comment by borice** [comment]
Just to clarify... if the `ValueConverter` is doing some non-trivial work to convert the command line argument into a particular structure, then having the `parse` method be called multiple times (with identical invocations) even though only a single command line argument should've matched this `ValueConverter` is wasteful.

**Comment by inkytonik** [comment]
I'm seeng this one as well. For some option o, each time I call o() the parser seems to run again, creating a new object in the value converter. Apart from the inefficiency of creating lots of extra objects, my code relies on the option value being the same throughout. I would have expected the conversion to happen just once, when the command line is parsed.

**Comment by inkytonik** [comment]
Thanks for this and the other changes leading to 1.0.0. It's good to see Scallop continuing.
