### ISSUE TITLE
trailArg ValueConverter not returning error message specified in Left(...)

### ISSUE THREAD

**Issue by borice** [scallop/scallop#87]
I have a trailArg[File] defined that I'd like to validate that the file exists, and output a relevant error message if it doesn't.  I see that there already exists a `fileConverter` defined, but the error message I get when the file specified does not exist is:  

```
[scallop] Error: Failed to parse the trailing argument list: 'texts/ocr_267_272/59/59259/269/17.xml' 
```

rather than something like:  

```
[scallop] Error: Failed to parse the trailing argument list: 'texts/ocr_267_272/59/59259/269/17.xml' - file 'texts/ocr_267_272/59/59259/269/17.xml' doesn't exist  
```

Using scallop 0.9.5

**Comment by clhodapp** [comment]
I've confirmed this as a legitimate issue to be fixed.

**Comment by Rogach** [comment]
New trailing argument parser will correctly handle such cases and output error like this:

```
Bad arguments for option 'file': 'nonexistent' - file 'nonexistent' doesn't exist
```
