### ISSUE TITLE
Strange (wrong?) handling of opt[List] with trailArg[List]

### ISSUE THREAD

**Issue by bobziuchkovski** [scallop/scallop#89]
I have a simple example that is behaving in an unexpected way.  I'm not sure if I'm missing something or if this is a bug.  Example:

``` scala
val args = Seq("--include", "path1", "--include", "path2", "file1", "file2")
val conf = new ScallopConf(args) {
  val include = opt[List[String]]()
  val files = trailArg[List[String]](required = true)
}

println(conf.summary)
// Expected: include => List(path1, path2), files => List(file1, file2)
// Actual:   include => List(path1, path2, file1), files => List(file2)
```

P.S.  Thanks for the library -- it's a great design!

**Comment by stevedlawrence** [comment]
`opt[List[String]]` will accept things like `--opt bar baz`. So specifying `--opt` multiple times isn't required to get multiple elements. This is why `file1` appears like it's part of `--include`. One solution is described in Issue #37, which is to define a new converter that makes it so your `--include` option only accepts a single argument, and you must specify the option multiple times (like you have in your example) to get multiple values. This would remove any ambiguity between `file1` being part of the include list or the files list.

**Comment by bobziuchkovski** [comment]
@stevedlawrence Thanks very much for the reply. That very much explains the behavior.  I'll go with the custom converter approach.
