### ISSUE TITLE
App exits when required params are not provided without giving a handle to the exception

### ISSUE THREAD

**Issue by ashwini-desai** [scallop/scallop#93]
We have a ScallopConf object that has some required options and some optional options. In case the required options are missing, an exception should be thrown. This is something we'd like to test in unit tests as well. However it appears that when a required option is missing, Scallop exits the system.

Example: Following code exits the app.

``` scala
try {
  new OurAppsCliOptions(Array())
} catch {
  case ex: Throwable => ex.printStackTrace()
}
```

It would be nicer if Scallop provided a configuration which disables the default exit behaviour.

**Comment by Rogach** [comment]
You can override [Scallop.onError](https://github.com/scallop/scallop/blob/develop/src/main/scala/org.rogach.scallop/ScallopConf.scala#L320) in your configuration object to get desired behavior.

Something like the following may work for you:

``` scala
protected def onError(e: Throwable): Unit = e match {
  case r: ScallopResult if !throwError.value => r match {
    case Help("") =>
      builder.printHelp
      sys.exit(0)
    case Help(subname) =>
      builder.findSubbuilder(subname).get.printHelp
      sys.exit(0)
    case Version =>
      builder.vers.foreach(println)
      sys.exit(0)
    case ex@ScallopException(message) => throw ex
  }
  case e => throw e
}
```

**Comment by colindean** [comment]
I ended up doing something like this as a test wrapper around my `CliOptions` class:

```scala
/**
   * This is necessary because [[org.rogach.scallop.ScallopConf]] defines errorMessageHandler
   * in a way that apparently an instantiation-time trait or redefinition cannot adequately combat.
   * @param arguments arguments as if they were passed on a CLI
   */
  class TestCliParams(arguments: Seq[String], throwing: Boolean = false) extends CliParams(arguments) {
    override def verify(): Unit = {
      installNonExistingErrorHandler()
      super.verify()
    }
    def installNonExistingErrorHandler(): Unit = {
      errorMessageHandler = { message: String => if(throwing) throw new Exception(message) }
    }
  }
```

And usage inside of a scalatest spec: 

```scala
    "have defaults" in {
      noException should be thrownBy {
        new TestCliParams(paramsWithDate)
      }
    }
    "reject a non-date" in {
      an[Exception] should be thrownBy {
        new TestCliParams(paramsWithBadDate, throwing = true)
      }
    }
```

In other places, I used some ADT instead of a boolean but found that using a named parameter was adequate for test code.

**Comment by Rogach** [comment]
@colindean There's something similar built-in, used in Scallop tests: https://github.com/scallop/scallop/blob/develop/jvm/src/test/scala/ScallopTestBase.scala

You can get similar behavior in your tests, by either wrapping individual invocations:

```scala
noException should be thrownBy {
  org.rogach.scallop.throwError.withValue(true) {
    new TestCliParams(paramsWithDate)
  }
}
```

Or you can use ScalaTest's BeforeAndAfter to alter the behavior for the entire test file, like here: https://github.com/scallop/scallop/blob/develop/jvm/src/test/scala/ScallopTestBase.scala (or if you don't care about cleanup you can just add a statement `throwError = true` at the top of the test, that will also work and will be much more concise).
