### ISSUE TITLE
If help comes after other options it says it's unknown

### ISSUE THREAD

**Issue by slavovojacek** [scallop/scallop#95]
e.g. `my-command --help` OK, but `my-command --an-option foo --help` gives `[scallop] Error: Unknown option 'help'`

@samthebest to watch

**Comment by Rogach** [comment]
I think that providing other options while simultaneously asking for help is probably indicating of a programmer error, and it might be a good idea to fail hard in this case.

If you really need this, I suspect that custom help option will work in this case (just define option with name "help").
