### ISSUE TITLE
How to validate that an option value is one of a finite number of whitelisted values?

### ISSUE THREAD

**Issue by boosh** [scallop/scallop#96]
Hi,

I don't understand the validation examples. I'm trying to validate that the value of an option is one of several predefined values:

```
val animal = opt[String](required = true, descr = "Must be either 'cat' or 'dog'.")
```

How can I do this with a scallop validation function?

Thanks

**Comment by ecurtin** [comment]
Use validate with a function that maps your String or Int or whatever to a boolean.
This is off the top of my head syntax, the following may not compile but it's the right idea.

``` scala
val animal = opt[String](required = true, descr = "Must be either 'cat' or 'dog'.", validate = x => someFunction(x))

def someFunction(x: String): Boolean = x match {
    case "cat" => true
    case "dog" => true
    case _ => false
}
```

**Comment by boosh** [comment]
Hmm I tried this no end of times but for some reason it's working today. Thanks.
